### ISSUE TITLE
Iran Hamzeh Training Ship x1

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1128]
### DB Selector

DB3K

### Hypothetical

No

### Name

802 Hamzeh

### Class

Chahsavar Class

### Country

Iran

### Service

Navy

### In Commission

1998-

### Length (m)

53

### Beam (m)

7.65

### Draft (m)

3.2

### Standard Displacement (t)

530

### Complement

??

### Primary Propulsion Type

Diesel

### Propulsion

2x GM Electromotive Div. 8-268A diesels

### Flank Speed (kt)

15

### Range (nm) at Speed (kt)

2500@10

### Sensors

- 1x Navigation Radar

### Mounts

- 4x C802 SSM
- 1x 40mm

### Comms/Datalinks

Standard

### Comments

Former royal yacht of the Shah of Iran, converted in 1998 to warship. Based in Caspian sea.

### Sources

https://en.wikipedia.org/wiki/IRIS_Hamzeh_(802)

![300px-Iranian_Navy_IRIS_802](https://user-images.githubusercontent.com/99632305/167237231-86fcb6d7-014e-473c-a2e0-f128358b75ba.jpg)
![Hamzeh](https://user-images.githubusercontent.com/99632305/167237290-62acc0e6-7470-4b6f-9296-fb9f7d5e05e3.jpg)
![Dk4GsLiWsAAdoUD](https://user-images.githubusercontent.com/99632305/167237304-5f7c1b0d-85d5-467e-a715-1782b9cd79d9.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 495. Gave it a 20mm gun instead of 40mm since all sources seem to indicate 20mm.

It clearly has two sets of triple torpedo tubes in the pictures, but I can't find any mention of them anywhere and I have no idea with what, if anything, they're loaded with. I've given it two triple Mk32s w/ Mk46 LWT Mod 2s which is certainly wrong but I haven't the foggiest idea what to give it instead. Will gladly replace if I get any better info.
