### ISSUE TITLE
Japan Coast Guard Shikishima (Upgraded) x5

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#1172]
### DB Selector

DB3K

### Baseline

3026 DB3K

### Hypothetical

No

### Name

PLH 32 Akitisushima

### Class

Shikishima Class

### Country

Japan

### Service

Coast Guard

### In Commission

2013-

### Length (m)

150

### Beam (m)

16.5

### Draft (m)

7

### Standard Displacement (t)

7175

### Full Displacement (t)

9350

### Empty Displacement (t)

6500

### Complement

140

### Primary Propulsion Type

Diesel

### Propulsion

2x IHI-SEMT-Pie;stick 16 PC2.4 V400

### Flank Speed (kt)

25

### Range (nm) at Speed (kt)

20000@18

### Sensors

- 1x JMS 1596 navigation radar
- 1x JMA 8303 surface search
- 1x JMA 3000 helicopter contros
- 1x Melco OPS-14C Surface/air search

### Mounts

- 2x twin 35mm/90 Oerlikon AA
- 2x single 20mm JM-61MB Sea Vulcan gatling AA
- 2x single 12.7mm M2 mg

### Aircraft & Docking Facilities

- 1x landing pad
- 2x hangar for AS.332L1 Super Puma or EC-225 Super Puma Mk II helicopters
- 2x davits for RHIBS

### Comms/Datalinks

Same

### Comments

Second unit ordered and delivered 2013, Reimel commissioned in 2020, Akatsuki in 2021 and Asazuiki scheduled for 2021

Like preceding PLHs, they have a long forecastle, but its internal structure is strengthened that the level of vulnerability resistance is comparable to warship standard. Bulletproof of the bridge structure is pretty much taken into consideration, polycarbonate bulletproof glass is prepared inside the window, metal fittings for the ballistic board are also attached to the outer wall.

### Sources

https://en.wikipedia.org/wiki/Shikishima-class_patrol_vessel
Combat Fleets of the World 16th Edition, page 383

![Shishima_PLH31_-_Japan_Coast_Guard_-_July_7_2007](https://user-images.githubusercontent.com/99632305/168145965-8546119f-a9b7-4348-872b-f30d21a66f6e.jpg)
![300px-JCG_Akitsushima(PLH-32)_left_front_view_at_Port_of_Kobe_July_9,_2017_01](https://user-images.githubusercontent.com/99632305/168145907-e197d2ab-2b09-4e17-add0-c03a0f99d3c3.jpg)
![300px-JCG_Reimei_(PLH-33)](https://user-images.githubusercontent.com/99632305/168145923-82fad358-8d87-43d6-898e-15cbc028ef8f.jpg)

**Comment by PygmalionOfCyprus** [comment]
Added 495.

Actually, the Wikipedia is quite wrong on the fit for the Akitsushima. Aki is technically a Shikishima-class vessel, but the JCG treats it as its own class since it was built 25 years later. It's got some non-negligible differences to weapons and sensors from Shiki: most notable is the replacement of the dual 35mms by 2x 40mm (Mk3s, I think, based on turret shape), upgrade of the optronics for the JM61-RFS (they're using the full "binocular" mount now, plus they've added more as far as I can see), and removal of the OPS-14. I'm sure they've refit the nav/SS radars too, but I have no idea what those are so I've left them as default for the moment.

You can actually see the differences in the pictures you posted: the first picture is PLH 31 (Shiki) and the latter two are for PLH 32 (Aki).

**Comment by PygmalionOfCyprus** [comment]
Oh, while I was at it I made some adjustments to Shikishima as well, notably overhauling and reworking our modelling of the JM61-series guns.

**Comment by cdnice55** [comment]
Thanks! This one had me running around since my CFW is 10 years old and only had info for #31 and #32 in it. Had to rely on Wiki for the other stuff. Glad you were able to differentiate them.
