### ISSUE TITLE
Dipping sonar update for Z-9C Haitun

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#1386]
### DB Selector

DB3K

### Affected DBID(s)

4826 Z-9C Haitun (China - 2010)

### Summary of Changes

-replace the AN/AQS-13B (DBID 2937) with AN/AQS-22 (DBID 625) as it were seen carrying a new dipping sonar with similar design.
![image](https://user-images.githubusercontent.com/99646926/174475682-6fe99e58-cf0c-46b6-82c8-9b7506451b9c.png)

### Sources

http://chinese-military-aviation.blogspot.com/p/helicopters-i.html

**Comment by PygmalionOfCyprus** [comment]
This isn't technically an "update" but rather a "copy," as it should involve creating a new entry rather than changing an existing one. (The new sonar was only spotted in 2015 so it wouldn't be accurate to install it on all the Z-9Cs in the DB.)

That said, the Z-9Cs needed some TLC, and while I didn't heal them completely I did give them a nice hug. I've swapped out the placeholder AN-AQS-13B for the China Type 605 dipping sonar, added specificity to the 2010 anti-piracy mod. version, and generally cleaned up the backend notes, etc.

One day I'll double back and clean up / fill out the family properly.
