### ISSUE TITLE
SU-27 prototype T-10

### ISSUE THREAD

**Issue by B-30F9** [PygmalionOfCyprus/cmo-db-requests#1392]
### DB Selector

Both

### Hypothetical

Yes

### Name

T-10 Flanker-A

### Country

USSR

### Service

Air Force

### In Commission

Never into service

### Number in Service

1

### Length (m)

DNS But it maybe simular to SU27

### Wingspan (m)

DNS But it maybe simular to SU27

### Height (m)

DNS But it maybe simular to SU27

### Empty Weight (kg)

DNS But it maybe simular to SU27

### Maximum Takeoff Weight (MTOW) (kg)

DNS But it maybe simular to SU27

### Crew

1

### Propulsion

The same as SU27

### Service Ceiling (ft)

DNS

### Military/Afterburner Speed (kt)

DNS

### Cruise Speed (kt)

DNS

### Supercruise

Yes

### Ferry Range (nm)

dns

### Sensors

simular to SU27

### Mounts

simular to SU27

### Loadout Options

simular to SU27

### Sources

It's a pitty that I can't not go to WIKIPEDIA to check data in China. But I'm sure you can find data in SU27 pages

**Comment by PygmalionOfCyprus** [comment]
I don't think this differs enough from the production Su-27 variant to warrant adding, especially since it was basically just a test platform for Sukhoi and not anything that might have served a combat role. I'm not opposed to adding prototypes when they differ significantly from the final product, but as far as I can tell other than being the first there was nothing particularly unique to the T-10.

Do feel free to correct me if I'm wrong, but for now I'm gonna close this as wontfix.

**Comment by B-30F9** [comment]
> I don't think this differs enough from the production Su-27 variant to warrant adding, especially since it was basically just a test platform for Sukhoi and not anything that might have served a combat role. I'm not opposed to adding prototypes when they differ significantly from the final product, but as far as I can tell other than being the first there was nothing particularly unique to the T-10.

 But it is much different than the final su27, and what's more, I notice t-50 was made in the game.

**Comment by PygmalionOfCyprus** [comment]
The T-50 really shouldn't be in there, IMO. It's just an Su-57 with a different name; indeed, in the DB there's no difference between the two. I'd delete it if I was able to (unfortunately we can't delete anything in the DB due to needing to preserve compatibility with older scenarios).

You say it's "much different than the final su27". Could you give some examples? Your initial request implies it's functionally identical: every field is just "similar to SU27".

If there are indeed _significant_ differences between the prototype and production model I'd be happy to reconsider.

**Comment by B-30F9** [comment]
> The T-50 really shouldn't be in there, IMO. It's just an Su-57 with a different name; indeed, in the DB there's no difference between the two. I'd delete it if I was able to (unfortunately we can't delete anything in the DB due to needing to preserve compatibility with older scenarios).
> 
> You say it's "much different than the final su27". Could you give some examples? Your initial request implies it's functionally identical: every field is just "similar to SU27".
> 
> If there are indeed _significant_ differences between the prototype and production model I'd be happy to reconsider.

My fault. I will look for more data.
Accroding to Russian, T-10 is much worse than F-15. I will delete this posts and write it again

**Comment by B-30F9** [comment]
> The T-50 really shouldn't be in there, IMO. It's just an Su-57 with a different name; indeed, in the DB there's no difference between the two. I'd delete it if I was able to (unfortunately we can't delete anything in the DB due to needing to preserve compatibility with older scenarios).
> 
> You say it's "much different than the final su27". Could you give some examples? Your initial request implies it's functionally identical: every field is just "similar to SU27".
> 
> If there are indeed _significant_ differences between the prototype and production model I'd be happy to reconsider.

My fault. I will look for more data.
Accroding to Russian, T-10 is much worse than F-15

**Comment by B-30F9** [comment]
> The T-50 really shouldn't be in there, IMO. It's just an Su-57 with a different name; indeed, in the DB there's no difference between the two. I'd delete it if I was able to (unfortunately we can't delete anything in the DB due to needing to preserve compatibility with older scenarios).
> 
> You say it's "much different than the final su27". Could you give some examples? Your initial request implies it's functionally identical: every field is just "similar to SU27".
> 
> If there are indeed _significant_ differences between the prototype and production model I'd be happy to reconsider.

What's more I found the Flanker family is much complexer than we think. Many different update were done even in a prototype (just like American fighters' different Block)
