### ISSUE TITLE
GJ-11

### ISSUE THREAD

**Issue by B-30F9** [PygmalionOfCyprus/cmo-db-requests#1407]
### DB Selector

DB3K

### Affected DBID(s)

4962 4961 4963

### Summary of Changes

GJ-11 can be proved to be a real plane now.
What's more. US satellite comfirmed that GJ-11 carrier version is developing

### Sources

https://bkimg.cdn.bcebos.com/pic/6609c93d70cf3bc7488422eade00baa1cd112a34?x-bce-process=image/watermark,image_d2F0ZXIvYmFpa2U4MA==,g_7,xp_5,yp_5/format,f_auto

**Comment by B-30F9** [comment]
link:https://baike.baidu.com/item/%E6%94%BB%E5%87%BB-11%E6%97%A0%E4%BA%BA%E6%9C%BA/23782502?fr=aladdin

**Comment by PygmalionOfCyprus** [comment]
I assume this is a request to unmark them as hypothetical?

I'm going to keep the hypothetical markers on for now, not because the aircraft's existence is in question, but rather because we don't know much/anything about their fit, specs, etc. and so our _DB entry_ is primarily hypothetical. (This is generally how we handle early/prototype/not-yet-fielded platforms in the DB.)

I'm also going to hold off on a carrier-capable version until we see more evidence of this, but am very open to adding it in the future even as a hypothetical if it does turn out to be a genuine project and not just a proof-of-concept.
