### ISSUE TITLE
Trophy OODA should be shorter

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1476]
### DB Selector

DB3K

### Affected DBID(s)

weapon ID 3137, facilities 3516,3517,2447,2979

### Summary of Changes

Trophy OODA is much longer than the flight time of things fired at it. Need to adjust. Its an automated system.

### Sources

File attached.
[Trophy OODA loop.zip](https://github.com/PygmalionOfCyprus/cmo-db-requests/files/8986979/Trophy.OODA.loop.zip)

**Comment by PygmalionOfCyprus** [comment]
This is a limitation of the "ground-units-as-mounts-as-facilities" system. Because the Trophy system is just one weapon record on the mount, I can't adjust it independently: giving it the "fully autonomous" property and corresponding near-instantaneous ODOA would also apply to all other weapons on the tank, effectively giving you a platoon of hyper-deadly Terminator Leopards.

The separately-modelled Trophy used for Ground Units is appropriately autonomous.

**Comment by bostonmyk** [comment]
Ok
