### ISSUE TITLE
LHA 8 Bougainville: Combat System-OODA Inconsistency

### ISSUE THREAD

**Issue by Zomorudas** [PygmalionOfCyprus/cmo-db-requests#1479]
### DB Selector

DB3K

### Affected DBID(s)

#3129

### Summary of Changes

LHA 8 has a fourth generation combat system (CS), yet a targeting time of between ten and two seconds, depending on proficiency. Such an OODA range appears reserved for a sixth generation CS, when comparing to other ships with a fourth or sixth generation CS. The time range is surely accurate, so it looks like the CS needs improving to sixth generation, matching its impressive speed.

Possibly, this is all wrong, and the entry is fine, or it has already been amended in a newer database. If not, let me know, because there are several other ships like this (including modern destroyers with old CS but blistering targeting speed), for which I will write more adjustments.

Connectedly, there are some modern auxiliary ships with fittingly modern CS generations, but very slow reaction times--the opposite configuration as the example above. Presumably, this is intended, and CS is not meant to designate precise, uniform OODA value ranges for every type of vessel, otherwise I can get after those, too.

### Sources

Intuition.

**Comment by PygmalionOfCyprus** [comment]
Are you using the old "OODA Targeting Time" value in the DB viewer to determine a ship's targeting time, or observing it in-game? If the former, this may be an issue of poorly-presented information.

The old "OODA Detection/Targeting/Evasion" time values haven't been updated to account for the new CS Generations. (Actually, they've been intentionally preserved in order to maintain balance in older scenarios.) The CS Generations come with their own set of values that _supercede_ the old ones.

Here they are:
<img width="1193" alt="Screen Shot 2022-06-27 at 11 39 47" src="https://user-images.githubusercontent.com/87087226/175849810-7f9c38e1-158c-48b5-af81-8efec2ab67ac.png">

I'll suggest to the other devs that we change the way this info is presented so that it's clear which set of values are actually being used.

**Comment by PygmalionOfCyprus** [comment]
I will, however, readily admit that in our initial "backfill" of CS Generations, we are certain to have made some mistakes. Most likely this involved giving modern destroyers lower-than-deserved CS Gen values (due to class-name matching, e.g. the Arleigh Burke-class may be 80s vintage but it's definitely been upgraded since then, and that wasn't reflected in our initial pass).

So, if you do see ships with incongruant CS Gens, please feel free to let us know.

**Comment by PygmalionOfCyprus** [comment]
No, bot, I was not answering my own question...

**Comment by PygmalionOfCyprus** [comment]
Have passed on to the other devs and opened a ticket in the Dev Mantis; there should be a clarifying update for the DB Viewer soonTM.

**Comment by Zomorudas** [comment]
Marvellous! Yes, was referring to the DB viewer targeting time numbers. Excellent to know that behaviour is governed by the new system, not the old numbers, and additionally that the confusion will be remedied. Will proceed with checking CS generations.

**Comment by PygmalionOfCyprus** [comment]
When/if you find CS Gen issues, it'd be best to lump it all together in one big request; that'll let us tackle everything in one go instead of sorting through a billion different 2-second tickets.
