### ISSUE TITLE
AAM-4, Rename, Seeker

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1686]
### DB Selector

DB3K

### Affected DBID(s)

4032, 1199

### Summary of Changes

Name:
remove "Kai" from name of AAM-4. 
Kai(改) means modification or improvement. Ex, F-4EJ Kai means F-4EJ Mod.

AAM-4B... we call it Type 99 Kai instead of AAM-4B Kai... can you move Kai after the Type 99(like Type 99 Kai) or just delete it?
I am asking this because AAM-4B Kai sounds like modification of AAM-4B... (bit picky but really weird in Japanese aspect, sry)

Sensor
AAM-4B's seeker is AESA radar with 1.4x Radar Seeker range. Quick Question. can we put AESA code for missile seekers?
It gives ECCM capability and resistance to radar notching maneuver.

### Sources

https://warp.da.ndl.go.jp/info:ndljp/pid/11488652/www.mod.go.jp/j/approach/hyouka/seisaku/13/jizen/honbun/19.pdf
Last page there is a comparison between AAM-4, AAM-4B, AIM-120B, AIM-120B+(C?),AA-12, AA-12PD
AAM-4B extends stand off range by 1.2x from AAM-4.
Self Guiding = seeker range become 1.4x from AAM-4 or AIM-120B/Cs.

**Comment by PygmalionOfCyprus** [comment]
Handled 496. I just removed the "Kai" completely since, as you say, it's redundant if we're already indicating the AAM-4B as a "Type 99 Mod" in English.

Weapon range was already good but adjusted the seeker range. And, speaking of the seeker --
> can we put AESA code for missile seekers?

-- yes! In fact, the AAM-4B seeker _already_ has the AESA flag. 🙂

**Comment by KC45jp** [comment]
Thanks！
