### ISSUE TITLE
Update/correction for HIMARS battery

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#1780]
### DB Selector

DB3K

### Affected DBID(s)

HIMARS(3204, 3384, 2807, 1968, 2446, 3268(PrSM), 3380(PrsM Spiral 1), 3381 (PrsM Spiral 2), 3382 (PrsM Spiral 3) 

### Summary of Changes

-Change the M142 HIMARS capacity from maximum of 6 to just 1. The launcher only have space for 1 missile/rocket pod as opposed to M270 MRLS launcher that have 2.

![image](https://user-images.githubusercontent.com/99646926/179385104-36cac4de-c6fc-49de-8d5e-6d270d556ca5.png)

![image](https://user-images.githubusercontent.com/99646926/179385168-cb897f41-aa6e-46da-906d-235d4b1cf20c.png)

-Add magazine for 24x M30A1/M31 GMRLS and 3x ATACMs Blk I / Blk IA (or 3x PrSM for the one that have it in the first place) for M142 HIMARS battery.  The system have its own reloading vehicles and the rockets can be reloaded around 5-10 minutes

![image](https://user-images.githubusercontent.com/99646926/179385376-38619a14-d3e5-41db-a85e-47ca643f2484.png)

![image](https://user-images.githubusercontent.com/99646926/179385529-d4744b7b-2a82-498d-8fdd-18cb4e255485.png)

![image](https://user-images.githubusercontent.com/99646926/179385640-11b43f9b-a899-4b75-9e6c-b3ae96f20031.png)

### Sources

https://www.joint-forces.com/features/44362-spring-storm-in-the-baltic-region-part-two-fires-shock
https://www.armedconflicts.com/M142-HIMARS-t201560
https://usdefensestory.com/steel-warriors-setting-the-standard-while-preparing-for-artillery-table-xv-live-fire/
https://ukrainetoday.org/2022/07/15/himars-in-action-russians-have-dramatically-reduced-the-number-of-shelling-due-to-the-loss-of-ammunition-depots/

**Comment by PygmalionOfCyprus** [comment]
Weapon records are based on weapons (i.e. rockets), not pods, so for most of the HIMARS mounts the current records are correct: six rockets, or one pod, vs. the M270's twelve. PrSM also fits [two to a pod](https://www.lockheedmartin.com/en-us/products/precision-strike-missile.html), unlike ATACMS.

I did, however, check all the HIMARS mounts and catch a case of double-loading for the Singaporean version, so there's that.

Added magazines as requested, though w/ 8x PrSM (when necessary) due to aforementioned pod distribution.
