### ISSUE TITLE
Update to Submarine Noise Levels: GATO class submarines (and possibly all WWII era-subs)

### ISSUE THREAD

**Issue by CV60LCC19** [PygmalionOfCyprus/cmo-db-requests#1832]
### DB Selector

CWDB

### Affected DBID(s)

Submarine_160, 462;

### Summary of Changes

As part of the revision of submarine noise levels, I'm beginning with verified noise levels of some WWII era subs.  The attached data is from "Urick, Robert J., "Principles of Underwater Sound", (3rd ed), pg. 350. A image of the relevant page is attached.   It gives the sound levels **on electric drive** of the following WWII era subs: USS HAKE and USS RUNNER (SS-256 and Ss-275 GATO class), USS S-48 (S-class) and HMS GRAPH (a captured German VIIC boat.  See https://en.wikipedia.org/wiki/HMS_Graph).  The US subs have noise levels at 200Hz at the surface from 145db @15knts to 125db @6knts.  At Periscope depth, the noise varies from 145db@10 knots to 130db @ 4knts.

Noise levels at 200 Hz for the Type VIIC boat HMS GRAPH on the surface varied from 150db@7knts to 160db @15 knots.  At periscope depth, the values were 160db@11knts and 140db @4.7 knts.

From this information, it appears the listed database values of US and German WWII submarines on battery are considerably louder/noiser than the 115 db given in the database.  Using these updated known figures for a GATO-class, I in subsequent posts begin to estimate the noise levels of early cold war Soviet submarines.  However, given the relatively close agreement between 1920's era S-boats, WWII era GATO class submarines and German Type VIIC Uboats, it may be worth simply increasing all sound levels for WWII era submarines to approximately 150-160 db, absent contrary information.

![sub noise001](https://user-images.githubusercontent.com/99547401/180267594-eed0e1b2-3c5a-4079-8233-dd0af6407c3c.jpg)

### Sources

"Urick, Robert J., "Principles of Underwater Sound", (3rd ed), pg. 350.

**Comment by PygmalionOfCyprus** [comment]
I'm really grateful to you for doing this. When we did our signature overhauls for aircraft, etc. the submarine passive modifiers went pretty much untouched. So any sort of "generation adjustments" you propose will go a long way.

FYI here are the current "base" numbers/generations for passive sonar signatures, with dB values for VLF, LF, MF, and HF in that order. (I've hidden the side/rear sigs because those are just determined by the respective frontal #s.)

<img width="766" alt="Screen Shot 2022-07-22 at 09 14 59" src="https://user-images.githubusercontent.com/87087226/180335579-3f191d84-dc26-4ceb-9a94-f829ce83a69e.png">

So, I'll probably bump the "older diesel" generation up to...150/130/120/110?

**Comment by PygmalionOfCyprus** [comment]
Also, just for internal filing: related to #1739.

**Comment by CV60LCC19** [comment]
I think it might be best if I did a spreadsheet like yours, with my proposed values.  I could imbed citations as a note in the individual spreadsheet cells, with interpolations being with a note in the cell, as well as our confidence levels of the evaluation.  That way, we can track generation/submarine size/nation/#of screws to help refine our noise evaluations.  Send me a PM with your  email, and I will send you a proposed spreadsheet draft.  I'm "CV60" on the Matrix forum.

**Comment by PygmalionOfCyprus** [comment]
Closed as redundant to #1858
