### ISSUE TITLE
A/A APKWS IIA unable to fire at cruise missiles

### ISSUE THREAD

**Issue by KJohnston11** [PygmalionOfCyprus/cmo-db-requests#1833]
### DB Selector

DB3K

### Affected DBID(s)

3661

### Summary of Changes

Add cruise missiles to the valid target list, as they were tested against a simulated cruise missile, and intended for cruise missile defense prototypes

### Sources

https://www.thedrive.com/the-war-zone/31615/air-force-tests-laser-guided-rockets-in-the-air-to-air-role-to-shoot-down-cruise-missiles

"The F-16C, assigned to the 85th Test and Evaluation Squadron, part of the 53rd Wing at Eglin Air Force Base in Florida, conducted the test over a range off the coast of the state on Dec. 19, 2019. A BQM-167 target drone served as the simulated cruise missile threat."

https://www.military.com/daily-news/2019/12/23/f-16-shoots-down-drone-test-new-cruise-missile-defense.html

An F-16 Fighting Falcon fighter jet has taken out a drone using an AGR-20A Advanced Precision Kill Weapon System (APKWS) laser-guided rocket in a first-of-its-kind test. The weapon could prove to be an alternative for cruise missile defense, according to the Air Force's 53rd Wing.

**Comment by KC45jp** [comment]
#1187 Related

**Comment by KJohnston11** [comment]
> #1187 Related

ah, shame it has been so long! looking to use this in a campaign i am making, along with LANCE Pod.

**Comment by PygmalionOfCyprus** [comment]
I'll bump it up on the priority list and try to have a fix for #1187 and this for 496. It's basically going to take an entire workday just for the one ticket, so I keep putting it off.

**Comment by KLABDB3K** [comment]
The issue is that it is the combination of the fast jet F-16 with a sufficiently advanced targeting pod which has been manoeuvred into the right position on a test range and able to maintain the correct FOV from the same advanced pod to keep the target illuminated that results in the cruise missile being hit. 
It is not inherently just that the APKWS fired from any platform with any pod within any parameter would be able to hit a cruise missile. Otherwise any laser guided rocket with sufficient kinetic performance could be tagged with the same capability.

**Comment by PygmalionOfCyprus** [comment]
"Remember @KJohnston11 when I promised to have this fixed for 496?"

![image](https://github.com/user-attachments/assets/cc66d211-abe1-4ffc-83bc-4c63aabcf5e8)

"I lied."

![image](https://github.com/user-attachments/assets/0993b92f-2589-4b01-8b0c-4af31c2ab5fb)

Handled 508.

![image](https://github.com/user-attachments/assets/c3f158f6-8b00-4811-a1cd-20edd79d7bf9)
