### ISSUE TITLE
MARS Tide Class - No fuel for refuelling.

### ISSUE THREAD

**Issue by 5th-Domain** [PygmalionOfCyprus/cmo-db-requests#192]
### DB Selector

DB3K

### Affected DBID(s)

#2581 - A 136 Tidespring [MARS Tide Cass] (United Kingdom - 2017)

### Summary of Changes

Should hold 19,000 m3 of fuel for replenishment. Not sure in the split between Diesel and Aviation Fuel that would be carried. 

Top Speed of 27+ Knots - Currently 22 Knots

### Sources

https://www.royalnavy.mod.uk/our-organisation/the-fighting-arms/royal-fleet-auxiliary/tankers/rfa-tidespring

https://www.engineeringtoolbox.com/fuels-densities-specific-volumes-d_166.html

**Comment by PygmalionOfCyprus** [comment]
Ship now carries 1000000kg of diesel and 600000kg of avgas. Approximated, definitely not accurate, but something vaguely in the vicinity of what you might get from 19000m3 of tanks. (I'm also unsure of the split.) Regardless, it should be good for fueling now.

Also updated the sensors (3x SharpEye sets rather than the generic radars it had before) and adjusted the max speed.
