### ISSUE TITLE
#2272 - Depth Charge - Sub PoH: 99%

### ISSUE THREAD

**Issue by HardLuck13** [PygmalionOfCyprus/cmo-db-requests#1958]
### DB Selector

DB3K

### Affected DBID(s)

#2272 - Depth Charge (25kg HE)

### Summary of Changes

#2272 - Depth Charge (25kg HE): Sub PoH: **99%**
This can not be correct for an unguided weapon. The Guided version: #2276 - RBU-6000 Salvo {R90, 12 rnds, Guided} has a Sub PoH: 30% & the #1124 - RBU-6000 Salvo {12 rnds} : Sub PoH: 15%
...or am I missing something?

-HL

### Sources

Just the CMO db build 476

**Comment by PygmalionOfCyprus** [comment]
It's actually *PoK*, not PoH. That is, Probability of Kill/Hit rather than Probability of Hit. Basically, what that's saying is "if you successfully hit a sub with a depth charge, you have a 99% chance of killing it (before modifications are applied). Actually hitting it is harder, as you point out: with a surface CEP of 150m, you're gonna have a hard time hitting even a confirmed target, let alone an uncertain one.

As for the discrepancy between the RBU-6000 salvos, those actually represent the initial salvo, which has a smaller CEP (20). So, basically, you have an initial salvo, which fires and rolls for hit; it has a lower chance of "kill" because it represents a wide spread, but if it does "kill," then that calls the individual depth charge with its own stats and a much higher POK -- because it assumes you've already passed a number of checks to get there in the first place.

...Anyway, it's complicated, but I believe this is WAD.
