### ISSUE TITLE
Various suggestions

### ISSUE THREAD

**Issue by trevor99999** [PygmalionOfCyprus/cmo-db-requests#1985]
Greetings all
Just a few suggestions. If any been covered in the last updates please excuse. **Thanks** for all your hard work.

Scenario Editor:
-Random variable start points for platforms
-Biologics can be set with random course and speed variables.
- Add SAR option for downed aircrew

Structures/Buildings/Maps:
-Roof top Helo pads
-Markers: Mega city: 5 000 000 DP; City: 500 000 DP; Town: 50 000 DP, Village: 5000 DP
-Large and Very Large Industrial Structures/Facilities (3000 - 5000 DP ?)
-Very large and/or very hard command/leadership bunkers (eg NORAD, Greenbriar, Mt Weather EOC etc)
-Saveable/copy-able template magazine contents and/or a total of munitions split between x number of shelters/pads etc that are available (similar to aircraft carrier etc magazines)
-Area surrounding Imperial valley, California is under water (negative sea level) example N32 51 06, W115 35 29, among other locations
-Richard Gebaur Air Reserve Station/Air Force Station/Memorial AP, closed since 1994, "whited out" on map.

Sensors:
- A visual display (radar range circle) of radar degradation due to jamming
- Visual display as to which radar emitters are radiating (without having to check the Contact Report)
- Intermittent sensors (in the old "Harpoon" series platform sensors could be set to intermittent)

Other:
- Time remaining counter until air-to-air refueling complete
- Notation as to which a/c can refuel from which type of tanker (Boom (B) or Probe and Drogue (P&B), or No Capability) eg AAR-B, AAR P&D, AAR-None
- Drop down glossary of acronyms etc
- "Fog of War" option relating to friendly ground units 
- An option to include "fratricide". AIM's and especially SAMs unerringly lock on to enemy a/c. Realistically, there would be exclusion zones around SAM sites, and there's always the possibility an AIM (especially a SARH) might lock on to a friendly a/c. 

- DB 494: Canadian a/c and ships should be Royal Canadian Air Force (RCAF) and Royal Canadian Navy (RCN), _not_ Royal Air Force/Royal Navy. Canadian Army, RCAF, RCN 1924 - 1968. CAF (Canadian Armed Forces) 1968 - 2011. Canadian Army, RCAF and RCN 2011 - present.

**Comment by KC45jp** [comment]
1
It sounds like some of the questions are more CMO game design requests... Not DB, so I guess you want to post them at here.
https://www.matrixgames.com/forums/viewtopic.php?f=10201&t=341588

2
We already have
>Notation as to which a/c can refuel from which type of tanker (Boom (B) or Probe and Drogue (P&B), or No Capability) eg AAR-B, AAR P&D, AAR-None (as Aircraft codes(properties), Probe Refuelling, Boom Refuelling, Centerline Drogue, Wing Drogue, Centerline Boom)
>Random variable start points for platforms

3
DP for city Markers... I think they are in DB mostly for checking the hits of Nuclear Weapon, so giving a lot of DB might not helpful.

**Comment by PygmalionOfCyprus** [comment]
Confirming this is pretty much all not DB stuff, but I'll respond anyway since you went to the trouble:

>- Random variable start points for platforms
>- Biologics can be set with random course and speed variables.
>- Add SAR option for downed aircrew

All easily doable through Lua (or, in the case of the biologics, just by assigning them to a patrol mission); the SAR feature specifically is done so frequently you wouldn't even have to look hard for the code.

>- Roof top Helo pads

Add an aircraft facility to the buildings you want the player to be able to land on.

>- Markers: Mega city: 5 000 000 DP; City: 500 000 DP; Town: 50 000 DP, Village: 5000 DP

Agree w/ @KC45jp on this one; town/city markers are just there as reference points or to get vaporized so we don't really need to build them out any further than they currently are.

>- Large and Very Large Industrial Structures/Facilities (3000 - 5000 DP ?)
>- Very large and/or very hard command/leadership bunkers (eg NORAD, Greenbriar, Mt Weather EOC etc)

Fair suggestion, but I think getting into the weeds on "different size versions of X structure" is a slippery slope. Re: NORAD, etc. -- if you're fighting a conventional war you'd be better off marking the tunnel entrances (which there are already facilities for); if you're trying to make nuke targets you may as well just use the usual underground facility marker since it'll get poofed anyway.

>- Saveable/copy-able template magazine contents and/or a total of munitions split between x number of shelters/pads etc that are available (similar to aircraft carrier etc magazines)

Not a bad idea. But not a DB thing, so can't help you here. Post in the forums.

>- Area surrounding Imperial valley, California is under water (negative sea level) example N32 51 06, W115 35 29, among other locations

This is on the terrain data provider we use, we can't do anything about this...though we have been experimenting with locally definable terrain. So maybe one day there'll be a workaround, if this particular area is critical to a scenario of yours.

>- Richard Gebaur Air Reserve Station/Air Force Station/Memorial AP, closed since 1994, "whited out" on map.

Not sure what you mean by this or what you want us to do about it.

>- A visual display (radar range circle) of radar degradation due to jamming

Not how radar jamming works.

>- Visual display as to which radar emitters are radiating (without having to check the Contact Report)

You can already turn this on in the display settings.

>- Intermittent sensors (in the old "Harpoon" series platform sensors could be set to intermittent)

Already a feature in the beta branch.

>- Time remaining counter until air-to-air refueling complete

Not exactly a "time remaining" counter, but you can see the fuel go up on the aircraft being refueled, which is effectively a progress bar. IMO this is a degree of detail that the commander (i.e., you) really should not be concerning themselves with.

>- Notation as to which a/c can refuel from which type of tanker (Boom (B) or Probe and Drogue (P&B), or No Capability) eg AAR-B, AAR P&D, AAR-None

Again, as @KC45jp notes -- already in the DB viewer. Check the aircraft codes.

>- Drop down glossary of acronyms etc

I assume you mean this for acronyms used in-game and not things in DB descriptions, etc. which would be a whole can of worms. For the most part any acronyms we use in-game are, I think, industry standard. In a simulation this complex there is an expectation of user familiarity. If there's a particularly egregious example that's not defined in the manual do let us know.

>- "Fog of War" option relating to friendly ground units

Like realistic sub comms, but for everyone? We want this, too. Will come with the comms overhaul...eventually.

>- An option to include "fratricide". AIM's and especially SAMs unerringly lock on to enemy a/c. Realistically, there would be exclusion zones around SAM sites, and there's always the possibility an AIM (especially a SARH) might lock on to a friendly a/c.

I like this and was actually just thinking about it myself. Definitely worth posting a thread over in the forums (not here, this is just for DB stuff).

>- DB 494: Canadian a/c and ships should be Royal Canadian Air Force (RCAF) and Royal Canadian Navy (RCN), not Royal Air Force/Royal Navy. Canadian Army, RCAF, RCN 1924 - 1968. CAF (Canadian Armed Forces) 1968 - 2011. Canadian Army, RCAF and RCN 2011 - present.

In the interest of not clogging up my enum tables with redundant information I think it's a fair abstraction to say the "Royal Air Force" of country "Canada" is the Royal Canadian Air Force. I don't see the need to specify country in OperatorService when we already define it in OperatorCountry.

**Comment by trevor99999** [comment]
Thanks for replying so quickly. Sorry to have put things in that weren't specific to the site application.

Re: Fog of War for ground units
More like ground units actually disappearing from the map and reappearing at intervals (intermittent radio contact?), and not necessarily being automatically identified as friendly. Not just being out of contact and unable to receive orders like subs. Especially for scenarios set in earlier time frames where a commander isn't quite as omnipotent as they are today. But I'll put this request in the forums with some of the above suggestions.

Regarding the RCAF designations, I'm assuming we can expect the Royal Saudi Air Force, Royal Norwegian AF, Royal Malaysian AF et al to be re-designated as just Royal Air Force? Yes? No? Maybe?

Kind regards
    On Wednesday, August 10, 2022 at 11:53:38 a.m. EDT, Ethan Hermanson ***@***.***> wrote:  
 
 


Closed #1985 as not planned.
