### ISSUE TITLE
Type 1 Submatrine Mobile Decoy

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#2000]
### DB Selector

DB3K

### Hypothetical

No

### Name

Type 1 Submatrine Decoy

### Length (m)

1.6

### Width/Span (m)

-

### Diameter (m)

0.152

### Weight (kg)

26

### Range (nm)

0.2

### Warhead

-

### Targets

Submarine

### Sensors

-

### Comments

late 2000 tech Torpedo decoy
I believe this is variant of MoD for surface ship but different program... have same size, similar weight. Perhaps, 26kg that shown in the source is rounded number of 25.6 kg.
https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/1581

Equipped by 8th Soryu class, Sekiryu, requested as  #2001.
Other Submarines,  ID, 673, 702, 703 have this, too.

System itself (include launching system) named as Torpedo Counter Measure (TCM), so we can use TCM for launcher name.

We have no detail for how much MoD do those subs, but I assume 4 while ship board variant have 4 of them in launcher.

### Sources

https://www.sankei.com/article/20170329-FTK2ZN7JUFKTJMTX2KH72WXLV4/

https://www.mod.go.jp/msdf/release/201805/20180524.pdf

**Comment by PygmalionOfCyprus** [comment]
Okay, I did something a little funky with this one. Since I agree that this appears (based on the info we have) to basically be the sub-launched version of the MOD, instead of creating a new weapon I've just added the name to the comments of the MOD and am using the same mount, etc. for subs as for surface ships (since I don't think it makes sense to create an identical copy of the weapon/mount for something that might turn out to basically be the same thing). I've indicated my thinking in the DB as well in case future developments prove us wrong and someone else has to fix my mess.

Added to SS 511 and the Taigei class in addition the the ZLQ-2Bs from #1999.
