### ISSUE TITLE
Russia Add SA-15 to Bykov Corvettes

### ISSUE THREAD

**Issue by HVAA** [PygmalionOfCyprus/cmo-db-requests#2058]
### DB Selector

DB3K

### Affected DBID(s)

#2890 - PK Vasily Bykov [Pr.22160] (Russia [1992-] - 2017)

### Summary of Changes

Add SA-15 to the Vasily Bykov class corvette (strapped/chained to helo deck)
It may not be a permament fit, but should be available for 2022 until this all finishes

### Sources

https://twitter.com/capt_navy/status/1534179570630393863?lang=en-GB
https://www.thedrive.com/the-war-zone/russian-black-sea-warship-now-equipped-with-ground-based-sam-system
https://www.thetimes.co.uk/article/russia-fits-surface-to-air-missiles-to-warships-to-protect-fleet-from-ukraines-british-supplied-anti-ship-weapons-bvzl3cz0c
https://newsbeezer.com/greeceeng/vasily-bykov-the-russians-installed-the-tor-air-defense-system-on-the-patrol-ship-pics/
https://www.ibtimes.com/desperate-russia-fits-warship-ground-based-missile-system-avoid-another-moskva-3533046

**Comment by KLABDB3K** [comment]
Plus the helicopter landing pad needs to be removed if the TOR is loaded otherwise you could just add it with an appropriate mount in the editor?

**Comment by PygmalionOfCyprus** [comment]
IMO these sorts of situational, "ghetto" mods should be handled in-editor rather than in-DB. It's sort of like the technical question. What happens if/when they roll off the SA-15 and roll on another SAM? Do we create a new entry every time the Russians glue something else to their helipads?

For the same reason we don't add new entries every time a new flattop gallumphs through the Strait of Hormuz with LAVs chained to the deck:
![image](https://user-images.githubusercontent.com/87087226/185891368-1682729b-7c74-4ff8-aa9d-d7727bda060a.png)


If it sticks around as a consistent change in Russian naval doctrine (or at least SOP for several years across the Black Sea Fleet) then it might warrant a spot in the DB "timeline," so to speak. But for now I think it's better handled in-editor by manually adding the mount and removing the pad facility.
