### ISSUE TITLE
Increase R-77M max range from 75 to 102nm

### ISSUE THREAD

**Issue by ghost** [PygmalionOfCyprus/cmo-db-requests#2079]
### DB Selector

DB3K

### Affected DBID(s)

3126

### Summary of Changes

sources indicate 190km as most common agreed upon max range (although longer ranges possible but not a consensus on that)

-increase max flight range to 102nm (190km)

Also, I've noticed the R-77M uses an AESA seeker so it should have wider FOV than the traditional monopulse doppler seeker of the R-77 and the AIM-120C. This should give it a FOV similar and possibly wider than the AIM-120D since the later does not use AESA seeker. Currently R-77 and AIM-120C both have ~45 degree FOV, meanwhile AIM-120D seems to have a 90 degree FOV. Maybe possible to increase FOV for R-77M to 90 degrees?

### Sources

https://militarywatchmagazine.com/article/su57-k-77-game-changer
https://aviationweek.com/defense-space/missile-defense-weapons/russia-unveils-video-modernized-air-air-missile
https://avisky.blogspot.com/2015/08/k-77m-new-russian-air-to-air-long-range.html
https://www.deagel.com/Defensive%20Weapons/K-77M/a002922

**Comment by LuigiP57** [comment]
Talking about field of view. I think PL-15/PL-15E should also have a 90 degree view since there have been a wide range of leaked evidence showing that this missile is eqiupped with AESA seeker. There is no barrier for China to achieve that.
https://en.wikipedia.org/wiki/PL-15
https://www.popsci.com/chinese-air-to-air-missile-hits-targets-spooks-usaf-general/ 
https://eurasiantimes.com/pl-15-missiles-us-air-force-urged-to-replace-sentry-wedgetail-awacs/
#1989

**Comment by LuigiP57** [comment]
#2081

**Comment by KLABDB3K** [comment]
> I'm not criticizing, I just doubt whether this range claim is solid. As far as I know, Russia uses a less strict standard (about 65000ft/1.5Ma target) than US and other countries (about 32000ft/1Ma target) when testing AAM. This results in the shrink of real-combat engage range of the missile.
> 
> So it would be better to remain as it be. :-)

Its a weapon designed with the objective of providing at least parity over peer systems such as the 120D and to catch up much lost ground. The premis that its performance is over egged has to be caveated by the fact that R27 was designed to outperform the Sparrow later versions and by most metrics such as range speed terminal guidance etc does and the R73 was desinged to out perform existing models of Sidewinder such as the 9L that were the bench mark of the day and by most metrics does (in terms of range and engagement envelope) . 
Sensor electronics wise R27/R73 whole new debate but in broad terms... 
Its not scientific proof and I appreciate the data on performance is always a hot debate but fundamentally the alternative is to say Russians know what the enemy has but are investing in a new system that they know cant beat an existing system like 120D let alone future proof it against systems to come?  From memory the figures for most western systems are best guesses due to the inherent sensitivty of the data and vast number of variables anyway?

**Comment by PygmalionOfCyprus** [comment]
Handled 507. Even if Russia is exaggerating the range slightly this seems to be the widely reported number and so what clients will expect.
