### ISSUE TITLE
R 33 Vikramaditya VLS Sam Update-Still Barak-1

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#2119]
### DB Selector

DB3K

### Affected DBID(s)

3629

### Summary of Changes

If no other updates have been made I'd push the Barak-8 date to 2025.

Barak-8 integration hasn't occurred just yet. See 2022 pictures-vids below of barak-1 launches.

Looks like 3x8 VLS for 24 total.
Looks like 2 medium and a small davit ports

### Sources

https://twitter.com/GuyPlopsky/status/1564990643616636928
https://i.redd.it/qfgz2p6wwqx41.jpg
https://www.pinterest.com/pin/793829871799282070/
https://twitter.com/amcaji/status/1562084416976928768

**Comment by PygmalionOfCyprus** [comment]
Updated 497. I've half a mind to mark the entry hypothetical, because I can't actually find any reliable indication that they are putting Barak 8 on the Vikramaditya other than a couple scattered references across some less-than-reliable Indian sources. (Read: terrible Youtube videos narrated by robot voices.) But it seems logical that it would happen _eventually_, so I'll hold off on that for now and just settle for the pushed-out IS date.

**Comment by bostonmyk** [comment]
Thanks! Vikramaditya is definitely the gift that keeps on giving.
