### ISSUE TITLE
IRGCN Shahid Soleimani catamaran

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#2182]
### DB Selector

DB3K

### Baseline

#3441 PGG Tuo Chiang of Taiwan

### Hypothetical

No

### Name

Shahid Soleimani catamaran

### Class

Soleimani class

### Country

Iran

### Service

IRGCN (IRGC Navy)

### In Commission

2022

### Number in Service

1 of a class of 3

### Length (m)

67

### Beam (m)

19

### Draft (m)

unk

### Standard Displacement (t)

600

### Complement

1 of 3

### Primary Propulsion Type

Diesel

### Propulsion

unkwnown

### Flank Speed (kt)

32

### Range (nm) at Speed (kt)

5000Nm @ cruise speed

### Sensors

1 WD-20 radar
1 Nav radar +1x smaller (probably commercial nav radar) Possibly 1x S band and 1x X band?
satnav

### Mounts

1x 30mm gun with a turret
It also has four manually operated guns that appear to be derived from the three-barrelled 20 mm M197 fitted to Iran's AH-1J attack helicopters. With two EO sensors.
[https://twitter.com/mhmiranusa/status/1568439653614731265/photo/4](url)

Television footage of the ship showed that it is fitted with four larger anti-ship missiles that are presumably either Noor (C-802) or the longer-range Ghader variant and two of a smaller type, possibly the Nasr (C-704) or the longer-range Nasir.
other report;
4x Ghader\Ghadir\Qader ASM (200-300 km range).
2x Nasr/Nasir ASM (35/90 km range).

2x chaff dispensers

6x VLS for possible future mid range SAMs (not operational yet!)
4x VLS for possible future short range SAMs (not operational yet!)
Also no Fire control radars present for SAMs on the ship. Possibly a future development.
“This is the Islamic Republic of Iran’s first domestically-developed warship which is equipped with the vertical launch, short-range and medium-range air defense systems,” Bagheri said,
[https://internationalaffairs.co/current-affairs/what-we-know-about-irans-newly-unveiled-catamaran-warship/](url)

### Aircraft & Docking Facilities

A Bell 412 and Bell 206 helicopter was seen landing on Shahid Soleimani'

Crane to deploy 3x small speedboat.
[https://twitter.com/imp_navigator/status/1566789460964122625 @ 0.53 seconds](url)
[https://twitter.com/mhmiranusa/status/1568439653614731265](url)

### Comms/Datalinks

VHF/UHF

### Ship Codes

Dual or Triple Stabilizers, Catamaran/Trimaran Multihull

### Sources

[https://www.janes.com/defence-news/news-detail/irans-irgcn-unveils-shahid-soleimani-catamaran](url)
[https://twitter.com/imp_navigator/status/1566787115014316032](url)
[https://twitter.com/imp_navigator/status/1566789460964122625](url)
[https://twitter.com/IranDefense/status/1566783767515201538](url)
[https://twitter.com/partisan2015en/status/1567208017048772613](url) thread

**Comment by tbrandon517** [comment]
Should probably be a update request as Shahid Soleimani is in the DB3K already.

https://[cmano-db.com](https://cmano-db.com/ship/3392/)/ship/3392/

**Comment by Huib18** [comment]
Oh that was posted quickly, Im surprised me, Sorry!

**Comment by tbrandon517** [comment]
Additional Coverage

https://www.thedrive.com/the-war-zone/what-we-know-about-irans-newly-unveiled-catamaran-warship

**Comment by KLABDB3K** [comment]
#3392 - Shahid Soleimani (Iran - 2022) WORK IN PROGRESS
DB3K 496. 
More accurately a corvette?
Twitter updates since this post based on photos and comments attributed to Iranian naval staff:
16 x Short Rage Navvab (??) SRSAM in VLS - this is an enigma - still trying to figure out what this is? 20km range
6 x Sayyad MR-SAM in VLS DB3K 3667 - Sayyad-2 - Based on radar and mast height would seem Bavar 373 unlikely? WIP
4 x Qader (Ghader) SSM port and starboard pairs firing offset forward. DB3K 2408 - Ghader [C-802 Mod]
2 x Nasr SSM single port and starboard firing offset forward. DB3K 2390 - C-704 FL-10 Nasr 1 (possible up to four if launchers are stacked?
4 x 20mm triple barrel gatling type two amidships each side - arcs per photos.
1 x RWS 30mm turret B position with EO system. approx 160 arc forward. 
2 x 12 barrel decoy launchers either side of 30mm gun mount. 
 
https://twitter.com/mhmiranusa/status/1568439653614731265?s=20&t=JGxYsrdRZ5N4qE7zZfS1vg

https://twitter.com/mhmiranusa/status/1579113902889373696?s=20&t=JGxYsrdRZ5N4qE7zZfS1vg



![soleimani FFL](https://user-images.githubusercontent.com/99494755/194953398-558fb4bc-df9d-4dd5-b736-8fab892cebd1.JPG)

![soleimani FFLARMS](https://user-images.githubusercontent.com/99494755/194953415-33feecd2-c13c-4913-9626-7c02e5287dbe.JPG)

**Comment by KLABDB3K** [comment]
https://www.navyrecognition.com/index.php/naval-news/naval-news-archive/2022/october/12314-iranian-irgc-navy-to-receive-new-heavily-armed-warships.html

**Comment by Huib18** [comment]
Navab missile was first mentioned together with the Zoobin AD system which is in development.
[https://twitter.com/Pataramesh/status/1449622412123848705?ref_src=twsrc%5Etfw](url)
[https://iranpress.com/content/55418/zoubin-short-range-air-defense-system](url)
But a radar for these missiles is still not present.

**Comment by Huib18** [comment]
Pls look at this system:
[https://twitter.com/HamedF39671643/status/1561767179216998401/photo/2](url)
The small Navab missile left and a vertical launch possible Taer family missile (SA-17 like??)

**Comment by PygmalionOfCyprus** [comment]
I've reviewed the ship; it's mostly up-to-date. The one thing I'm holding off on is the mystery Navab/Zoobin missiles; with no good data I can't really add them yet (and there's no radar anyway so frankly it's sort of a moot point). We're keeping a close eye on this particular vessel for updates and will call 'em as we see 'em.

**Comment by PygmalionOfCyprus** [comment]
Added the Zoobin/Navab in 500.
