### ISSUE TITLE
Hamina FAC VDS, Torp and SAM update

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#2209]
### DB Selector

DB3K

### Affected DBID(s)

3186

### Summary of Changes

Replace Mk.46 torpedoes with Tp 47 mounts
Add Kongsberg ST2400 variable depth sonar #6064
Replace 12.7mm with automated SAAB Trackfire 12.7mm
Downgrade to Umkhonto-IR SAM per previous. There is no indication it has Barak-8 yet.
Restore previous sensors. 

### Sources

https://www.navalnews.com/naval-news/2022/09/finnish-navy-receives-4th-and-final-hamina-class-fac/
https://www.janes.com/defence-news/news-detail/fourth-finnish-hamina-class-fac-completes-mlu

**Comment by Andratenor** [comment]
The problem is that the ship has got the loadout of the hypothetical Israeli Sa'ar 72-class, Ship #2719, so everything is wrong when it comes to sensors, EW, Mounts, Stores, Weapons, Comms, Datalinks and even air facilities (as the Hamina certainly has not got any helipad.

This has been the case since the Gabriel V missile was added.

The correct

**Comment by Jkryos** [comment]
Updated/Added DB3K 505.
