### ISSUE TITLE
Expeditionary Operations

### ISSUE THREAD

**Issue by sigs10** [PygmalionOfCyprus/cmo-db-requests#2693]
I am a retired USN Submariner. That is my specialty, but I am trying to understand the Amphibious operations aspects. I have come across a few issues that are frustrating to scenario planning.

1. Submarines have no cargo capacity. I would like to be able to deploy SOF units, but I can't even install them on boats. I especially tested the Ohio SSGN and Jimmy Carter SSN(SOF) and was unable to mount any units. Meanwhile, the cargo database says I can load an entire four car locomotive on an Arleigh Burke DDG.
2. The Database is haphazard. There are large gaps in basic unit types and then over detailing in certain trivial units. There are units that have zero PAX that should have dozens of personnel. Then there are units that should have smaller sizes. For example, Force Recon and SEAL units come in sizes the smallest of which is 10. Meanwhile, the UH-1 helicopters have a loadout of (8x SEALS) so I am unable to load a SEAL team. There are some other units that could substitute for these smaller units but just make SEAL/FORECON fire teams of 4.
3. Amphibious vehicles (AAV) have no clear means of deploying directly from the mothership. They wind up being ferried like any other vehicle, which is self-defeating. Meanwhile, I had a scenario (Hot Tamales) where ground vehicles were driving across Gitmo Bay as if it didn't exist.
4. When units are deployed, they are grouped as one unit called Landing Detachment. Can they be deployed or built into normal combat units, renamed, and regrouped.
5. The cargo database is terrible for filtering. It only has one text filter, yet it has multiple columns. How about filtering by these columns and maybe a few more, like type (infantry, armor, artillery, supply, recce, etc.), Insertion capability (Paradrop (you have that, but break it up into static line, HALO, HAHO, etc.) Fast Rope, Amphibious Vehicle (AAV)), Size (fire team, Squad, Platoon, Company, Battalion, etc.)
6. Create a means to load templated configurations of cargo much like you have templates for Airbases and Battle Groups. Having to crack out a JP 3-02 to build out an ARG is a little crazy.
7. Have a catalog like you have for the other units that provide some descriptive of the unit plus a picture. Like you have for all the ships, aircraft, radars, and weapons.
8. When airborne units return from their initial insertion, they go back and commence refueling ops which could take over an hour. Instead have them take onboard the next group of troops to ferry and immediately sortie. Don't refuel until they are at Bingo.
9. This game is amazing and is the pinnacle of major force operations. But look at Cities; Skylines and allow user mod support. I have seen shortcomings in this game since it rolled out 8 years ago that if it allowed crowd source input it could grow by leaps and bounds.

**Comment by tbrandon517** [comment]
I think you're going to like the upcoming cargo 2.0 in the warplanes update.

https://command.matrixgames.com/

But some comments by me on your points.
1. You can request updates here for specific submarines with an expected troop capacity. In the meantime you might try loading a boat into the DDS and adding the cargo to it.
2. As above you can submit a DB update here. The Dev team is very responsive. Since the GitHun tracker launched I myself have 200+ completed DB requests.
3. With the current beta or upcoming Warplanner release you amphibious vehicles will be amphibious. And ground navigation is improving.
4. Currently deploying ground units modeled as facilities has some issues like this. But I recall being able to use multiple aircraft to load a unit and get it to reform when landed with the current cargo model.
5. Currently cargo items are just units from the DB tagged as cargo. At present the ground stuff is going the be in facilities but soon you'll have the ground units index. The DB info with be there. I'm thinking the devs might say the insertion method is to granular for CMO. 
6. I like that idea as it in the vain of customization of formations and WRA settings that are upcoming
7. That's in the DB for the facilities and (upcoming) ground units.
8. Not sure if Cargo 2.0 will help you directly but it may provide a workaround, say by moving infantry units out of a base and the having a helo pick them up in the field near the home base.
9. I recall what the devs experienced with IP issues with HARPOON mods and why they keep the DB locked. I understand and support their position. I'm also unsure how PRO customers would feel (especially government customers) to the engine being open to crowd sourcing.

Just my $0.02

**Comment by PygmalionOfCyprus** [comment]
As usual tbrandon is on the ball.

Most of these requests should go on the forums as they're not DB related, but for specific DB issues, you can post 'em as individual tickets and we'll do our best to address them.

>The Database is haphazard

You're not wrong. We're doing our best to get it up to speed but that will take time; there are two of us working on the DB (one part-time) and a whole world's worth of equipment to add/update across over nearly 80 years of history. We'll continue the fight!
