### ISSUE TITLE
Make targeting pods and self defense missiles optional in strike loadouts

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#2713]
### DB Selector

DB3K

### Affected DBID(s)

All strike loadouts

### Summary of Changes

Make targeting pods and AAMs optional in strike loadouts. See SME post below.

### Sources

SME post

https://www.matrixgames.com/forums/viewtopic.php?p=5064810#p5064810

_The other problem at work is that the database of aircraft loads isn't completely realistic. There are usually more (often lighter) safe loadouts on an aircraft than the database depicts. That tends to push towards an overconsumption of some weapons. Over time, I'm seeing more and more aircraft with less than "full combat load," because it's a way of managing one's consumption of munitions. Some of that is helped by making certain weapons "optional." If I was going to revamp the database, I'd probably be a lot more liberal with my optionalities. Targeting pods? Optional. Self defense missiles? Optional? I generally like the guys' guideline that if you want to have a given aircraft configuration added to the database you need to send them a photograph of it. I think that's very smart. It's probably overly strict, but given the hundreds (or in some cases THOUSANDS) of possible ways of configuring a given aircraft, it's probably a wise decision to keep the database size reasonable and the amount of labor for maintaining it under control._

**Comment by PygmalionOfCyprus** [comment]
This isn't a feasible review request due to scale (esp. since the targeting pods are not _always_ optional, e.g. in cases where the laser is needed for guidance, etc.); it's not something we can safely handle with a quick query for fear of unexpected follow-on effects.

The real solution to this is dynamic loadouts. I have made a proposal for this and it is safely couched in the nebulous future when we're not swamped with pro work. [I am assured of this.](https://www.youtube.com/watch?v=l8y3kmdt2Z0)

**Comment by bostonmyk** [comment]
Ok sounds good. 

M
