### ISSUE TITLE
Reconfigurations for Bomarc and Nike missiles

### ISSUE THREAD

**Issue by FIM43-Redeye** [PygmalionOfCyprus/cmo-db-requests#313]
EDITED: Safeguard concerns removed, duplicate

### DB Selector

CWDB

### Affected DBID(s)

Bomarc and Nike missiles (665, 1547-1549, 825, 331, 1645)

### Summary of Changes

Bomarc missiles, ID 665, 1547, 1548, 1549, have passive instead of active terminal guidance. They should fire up their own seeker to track the enemy: as is, they have to be command guided all the way to the target and go dumb when they're commanded active, flying circles around the same spot until they inevitably fall out of the sky. The missiles already have an active radar seeker in the DB, so this shouldn't be too much of an issue.

Nike Ajax and Nike Hercules, ID 825, 331, 1645, should be command-guided.

### Sources

Bomarc internal seeker: [https://www.nationalmuseum.af.mil/Visit/Museum-Exhibits/Fact-Sheets/Display/Article/198024/boeing-cim-10-bomarc/](url)

MSR: [http://www.nuclearabms.info/Radars.html](url)

Nike Ajax missile behavior: [https://nuke.fas.org/guide/usa/airdef/nike-ajax.htm](url)
Nike Hercules missile behavior: [https://nuke.fas.org/guide/usa/airdef/nike-hercules.htm](url)

**Comment by tbrandon517** [comment]
Link ti #171

**Comment by FIM43-Redeye** [comment]
Bomarc issue still applies; edited.

**Comment by PygmalionOfCyprus** [comment]
Bomarc issue is fixed. No idea WTF was up with the seeker head, it looks like it was originally built as a SARH seeker and then just "switched" to active without actually filling in any of the radar stats. Ripped it out and replaced it with a proper AR seeker so it should work properly now.

Nike being SARH instead of Command guided is a symptom of #1265, mentioning it here so it gets linked to the relevant issue but we'll handle it when we get to dealing with all that mess.
