### ISSUE TITLE
J-20 Internal Long-Range Loadout Includes External Stores

### ISSUE THREAD

**Issue by BigHardHorns** [PygmalionOfCyprus/cmo-db-requests#3183]
### DB Selector

DB3K

### Affected DBID(s)

#27991 #27997 #28022 #28028 #28001 #28007 #15592 #25097

### Summary of Changes

J-20 "Internal Long-Range" loadouts include "4 x 1700 liter drop tanks", which must be carried externally

### Sources

(Apologies, I can't find anything that positively states that only the external hardpoints are 'wetpoints', but I have found nothing to suggest that there is any potential for carriage of drop tanks internally either)

**Comment by PygmalionOfCyprus** [comment]
Agreed re: your assumption, I think we can safely infer that there are not "internal-external" fuel tanks.

Also, in the future, please preface the "Affected DBID(s)" with an annex name as in the example (e.g., "Aircraft #27991 ... etc.") so that it can be auto-labeled.

**Comment by BigHardHorns** [comment]
Wilco, thanks for explaining what the annex is.

**Comment by PygmalionOfCyprus** [comment]
Just took a gander at these loadouts, I think there's a small misunderstanding. The fuel tanks are currently already set to external -- I thought you were saying they weren't, but I think you meant that they shouldn't have fuel tanks at all since those are inherently external? AFAIK the thinking behind these "Internal Long Range" loadouts is that it is an internal loadout when tanks are jettisoned, so you can use the tanks to get out farther but then jettison them when stealth becomes an issue.

**Comment by BigHardHorns** [comment]
Ah ok, yes you understood what I meant and I get it now. I just presumed someone could select an ‘Internal Only’ loadout and not have to consider what to drop when. My mistake, please go ahead and close that, unless you’d rather I do something with itSent from my iPhoneOn 8 Apr 2023, at 2:26 am, Ethan Hermanson ***@***.***> wrote:﻿
Just took a gander at these loadouts, I think there's a small misunderstanding. The fuel tanks are currently already set to external -- I thought you were saying they weren't, but I think you meant that they shouldn't have fuel tanks at all since those are inherently external? AFAIK the thinking behind these "Internal Long Range" loadouts is that it is an internal loadout when tanks are jettisoned, so you can use the tanks to get out farther but then jettison them when stealth becomes an issue.
