### ISSUE TITLE
3229. FFG 62 Constellation, United States, Navy, 2026

### ISSUE THREAD

**Issue by transientSG** [PygmalionOfCyprus/cmo-db-requests#3233]
### DB Selector

DB3K

### Affected DBID(s)

3229. FFG 62 Constellation, United States, Navy, 2026

### Summary of Changes

Update FFG-62 Constellation class VDS sonar to use CAPTAS-4 array. 

### Sources

https://www.navalnews.com/event-news/sna-2023/2023/01/thales-started-production-of-captas-4-sonar-for-us-navy/

**Comment by PygmalionOfCyprus** [comment]
Already updated as of 499.

**Comment by transientSG** [comment]
> Already updated as of 499.

The VDS sonar for the Constellation class in 499 still shows as the SQS-62 VDS, which is the DART which the USN decided to end development for. How is it already updated as of 499?

**Comment by PygmalionOfCyprus** [comment]
I'm sorry, I've just gone back to our 499 release and you're right. The issue was already fixed at some point in the 500 cycle; seeing that, I assumed it had been done back in a previous release.

Point is the Constellation has CAPTAS on the current working DB version and will be fixed in the next release. 😅

**Comment by transientSG** [comment]
No issue, thanks for looking into this!
