### ISSUE TITLE
Shahed-129 naval variant AKA Simorgh of Iranian Navy

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#3310]
### DB Selector

DB3K

### DBID to Copy

Aircraft 4377

### Hypothetical

No

### Name

Shahed-129 (Simorgh)

### Country

Iran

### Service

Navy

### Sensors

Same as Aircraft 4377

### Mounts

- Add chaff/flare dispenser
![image](https://user-images.githubusercontent.com/99646926/233213635-2b30bf77-1abc-4000-a5a3-81480792f8f6.png)

### Loadout Options

Retains existing Shahed-129`s loadout with addition to:

Recon [Generic SAR pod] loadout (Day/Night All-Weather)
- 1x Generic SAR pod (Weapon 3990)
![image](https://user-images.githubusercontent.com/99646926/233214103-f174c7d2-9de9-4a11-88b7-820c399d4c4c.png)
![image](https://user-images.githubusercontent.com/99646926/233216469-537f86a2-68dc-4417-93ad-b42919c99b0b.png)

Sonobuoy, Search-only (ASW Patrol) loadout (Day/Night All-Weather)
- 10x Generic Active Directional  Sonobuoy (Weapon 2553)
![image](https://user-images.githubusercontent.com/99646926/233215431-066d3dd3-969f-446b-b2dd-8c7ee5bf4e8c.png)

### Sources

- https://www.farsnews.ir/en/news/13990706000883/IRGC-Aerspace-Frce-Unveils-SAR-Radar-00-Km-Range-Navy-Ballisic
- https://twitter.com/Alfonso97193622/status/1204084602454913024
- https://twitter.com/mhmiranusa/status/1648720956741885954

**Comment by Halberx** [comment]
The mount you are referring to as a chaff/flare dispenser is actually the red LED navigation lights. Also, NEDAJA is not an user of the Shahed-129/Simorgh since March 20, 2022, according to an IRNA reporter. Number in (peak) service has to be 2 (S/N;027 and 030) and they were active from 2019-2022. No evidence of sonobuoy usage by NEDAJA Simorghs and SAR pod was carried by 030.

https://twitter.com/mohshaltouki/status/1634568201982885889
https://twitter.com/mohshaltouki/status/1634568201982885889

**Comment by PygmalionOfCyprus** [comment]
Handled 501.
