### ISSUE TITLE
USAF Block 40s got Hav Glass enhancements in 2020-2021

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#356]
### DB Selector

DB3K

### Affected DBID(s)

1756

### Summary of Changes

Aviano Squadrons (31st Wing-555, Buzzards) received Hav Glass Updates starting Oct 2020

### Sources

https://theaviationist.com/2020/10/15/the-555th-fighter-squadron-triple-nickel-has-its-own-have-glass-v-f-16c-aircraft/
https://vortex-images.com/articles/articles-2020/the-31st-fighter-wing/
https://defence-blog.com/storied-triple-nickel-fighter-squadron-completes-historic-deployment-to-qatar/

**Comment by PygmalionOfCyprus** [comment]
Need to rework the modifiers for this. Want to do this sooner rather than later.

**Comment by bostonmyk** [comment]
Ok there are a couple of big F-16"ee" things I'll add. I've been hesitating because its a lot of work (600 gallon fuel tanks). I'll add thinking you might have to dig in anyways due to some of this stuff but really sorry for the work and wish I'd caught this years ago during my shift!

**Comment by PygmalionOfCyprus** [comment]
![1512193705731](https://user-images.githubusercontent.com/87087226/156580156-5ab1c6f0-2d9d-43cd-bd4f-d694dcd008d7.gif)

**Comment by bostonmyk** [comment]
2022 Link of Aviano Vipers.  
https://twitter.com/stewartjack25/status/1506172578515361796

**Comment by PygmalionOfCyprus** [comment]
On hold pending PygmalionOfCyprus/cmo-db-dev#178.

**Comment by PygmalionOfCyprus** [comment]
I took this opportunity to do a deeper review of the F-16s and the Have Glass program. "Have Glass," indeed: I "Have Glass" right now because trying to figure out the dates when the USAF slathered RAM goo across their F-16s drives me to drink.

As best as I can tell the F-16CJ (now CM/DM) Block 50/52s got Have Glass II ages back -- like, back in the early '90s, when they were still splitting the radar/IR improvements into Pacer Mud and Pacer Gem respectively. So, I've gone through and applied HGII to all the Block 50/52 F-16CJ/CM/DMs. I have _not_ applied any IR modifiers to those aircraft because it sounds like Pacer Gem was pretty infrequently applied.

Then, in 2011/2012-ish it seems like they started putting Have Glass V onto those same platforms (though the intent is to eventually apply HGV to all the active Vipers). So, for now, I've applied it to all the 2011- F-16CJ/CM/DMs and will trickle it on to other versions as it spreads. Worth noting that on the HGV AC I _am_ applying a heavy coat of IR reduction since the F-35 paint is some fancy stuff with known significant IR reductive qualities.

Which brings us to the actual body of this ticket. I've created a new 2020 entry for the CM Blk 40 w/ HGV. Will do the same for the Dutch AC as mentioned in #345.

All this to say: added 494.
