### ISSUE TITLE
Adjust land facility 3537 mag weapons count down from 72 to 8 or something like that

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3625]
### DB Selector

DB3K

### Affected DBID(s)

Facility 3537

### Summary of Changes

Ukrainian Neptun weapons mag has 72 missiles in it. Likely 8 tops. Probably typo.

### Sources

![NeptunbigMag](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/7115648/998ce547-9bea-4b22-b0b1-cc5d795304e0)

**Comment by PygmalionOfCyprus** [comment]
Okay, see, this was actually intentional but I also think it's weird.

When I built this hypothetical battery I was working off of [this source](https://old.defence-ua.com/index.php/en/publications/defense-express-publications/8251-ukraine-has-created-new-missile-systems), which says:
>The composition of the Neptune Battery can be configured to meet specific Customer needs. A Neptune battalion would typically consist of: (1) mobile command and control post, (2) three launcher batteries consisting of two launchers USPU-360 each, (3) operational support battery consisting of six transporter/transloader vehicles each carrying one storage/transport/launch canister TPK-360, (4) logistical units. Each Neptune battalion will have a standard missile establishment of 72.

Needless to say there is some funky math going on here. 6 loader vehicles carrying 4 missiles each? That puts it at 48 missiles total /bty. Or 6 loader vehicles + some extra missiles carried by the mysterious "logistical units"? That could bring it up to 72 total.

No matter what I should definitely remove 24 missiles from the magazine to account for those on mounts already. Still seems to indicate a fairly large # of missiles was planned for these hypothetical batteries.

Needless to say this does not even come close to representing the operational reality of how these have actually been employed by Ukraine during the war.

**Comment by PygmalionOfCyprus** [comment]
Adjusted magazine load to 48 to make total amount 72 total instead of 96.
