### ISSUE TITLE
China, DF-27 IRBM/HGV update

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#3823]
### DB Selector

DB3K

### Affected DBID(s)

weapon 4317 4318 4319 4320 4321 4322

### Summary of Changes

Increase the current range from 3000nm to 4320nm. US intelligence indicate that it has a range "enough to strike Hawaii from Chinese mainland".

### Sources

https://www.scmp.com/news/china/military/article/3221198/chinas-advanced-df-27-hypersonic-missile-which-can-strike-parts-us-has-been-service-several-years
https://www.iiss.org/online-analysis/online-analysis/2023/05/intelligence-leak-reveals-chinas-successful-test-of-a-new-hypersonic-missile/
https://missiledefenseadvocacy.org/missile-threat-and-proliferation/todays-missile-threat/china/df-27/
https://www.defense.gov/CMPR/
#3135

**Comment by PygmalionOfCyprus** [comment]
The South China Morning Post has picked the absolute maximum possible range to yell about because "CHINESE MISSILE CAN HIT HAWAII" is a more dramatic headline than "CHINESE MISSILE CAN LIKELY STRIKE TARGETS BEYOND THE FIRST ISLAND CHAIN". The cooler reports from IISS and MDAA seem to concur that the range is likely much closer to the minimum (5000km) than the maximum. Gonna keep the range as-is for now.
