### ISSUE TITLE
Grass landing strips

### ISSUE THREAD

**Issue by trevor99999** [PygmalionOfCyprus/cmo-db-requests#3848]
Grass landing strips of various lengths  - example RAF Henlow

**Comment by FrangibleCover** [comment]
I've thought about grass strips, but I couldn't come up with a good way of doing them outside of designating aircraft as Grass-Capable in the same way as they get designated as Carrier-Capable. It's not a matter of landing distance (grass strips can be miles long) nor one of size (a C-130 will cheerily land on surfaces that would ruin most fighters), so we'd need a new database tag for all aircraft. Might as well have two, really, one for grass and one for 'rough surface' to cover gravel, PSP, unprepared highways and the like.

**Comment by PygmalionOfCyprus** [comment]
It's also tough because then you get into the whole mess of categorizing austere airfields. Some aircraft can take off from airfields with FOD but they still need concrete. Some can do dirt runways but not grass. Some can do grass but only under certain conditions. And so on.

It's sort of a slippery slope and at the end of the day it just comes down the what the sim is trying to achieve. Yes, in real life, you can land certain aircraft pretty much anywhere there is room. Are scenario designers to place appropriately-sized "landing strips" in every single field/clearing across the continent just in case?

I'm passing on grass/austere capability for now, but we are adding a road runway for 503 as part of a separate task, so there's that.
