### ISSUE TITLE
DF-41

### ISSUE THREAD

**Issue by HunterDNiu** [PygmalionOfCyprus/cmo-db-requests#3925]
### DB Selector

DB3K

### DBID to Copy

Weapon 3456

### Hypothetical

No

### Name

DF-41

### Country

China

### Service

Rocket Force

### Other Changes

_Change weapon to 3x warhead 1139._ 
"[T]he DF-41 ICBM will likely carry no more than three MIRVs."

### Sources

https://www.tandfonline.com/doi/full/10.1080/00963402.2023.2178713#

**Comment by claudejdev** [comment]
hey there,

from IHS Jane's Weapons Strategic 2021-2022. Coulsdon, Surrey, UK: IHS Global.
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/35732829/e97da941-7e68-4926-ba56-dbed2b4a893c)

**Comment by HunterDNiu** [comment]
> hey there,
> 
> from IHS Jane's Weapons Strategic 2021-2022. Coulsdon, Surrey, UK: IHS Global. ![image](https://user-images.githubusercontent.com/35732829/277620230-e97da941-7e68-4926-ba56-dbed2b4a893c.png)

I would not take a number that consonants CCP propaganda seriously.

**Comment by PygmalionOfCyprus** [comment]
I usually defend Janes but I will admit that they're not really good at actually digging into the numbers, they just sort of pull data they can find. We're guilty of that too, but then we're not Janes. (A lot of our entries are more accurate. 😎) 

I'm gonna knock it down to 3 because I trust the Nuke Notebook more than I trust the intern who Googled "DF-41 warhead count". If we get nuked and we see there are more than 3 MIRVs I'll post an update from the Command bunker.
