### ISSUE TITLE
China, PLAGF/PLAN, M20B ASBM

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#3980]
### DB Selector

DB3K

### Baseline

weapon 2878 2879

### Hypothetical

No

### Name

M20B ASBM

### Length (m)

same as DF-12

### Width/Span (m)

same as DF-12

### Diameter (m)

same as DF-12

### Weight (kg)

same as DF-12

### Range (nm)

same as DF-12 (it's OK to ignore the MTCR restriction)

### Warhead

same as DF-12

### Targets

Surface Vessel

### Sensors

1x Active radar seeker (early 2010s tech, similar to sensor 7149)
1x Passive radar seeker

### Comments

Surface PoH 90% maybe reasonable?

Also cut down its CEP surface to <10m for targeting surface vessels.

Solid source indicate that it's more like an HGV with lower mid-course altitude and glide trajectory. Maybe consider categorize it as HGV? However, one thing is for sure that the peak altitude of its trajectory is 50km. Also need to upgrade the original DF-12's cruise altitude (currently 152.4km).

Need mobile facility to carry it.

### Sources

https://missilethreat.csis.org/missile/df-12/
https://twitter.com/someplaosint/status/1722991571010728016
http://cndefense.com/tgaws/M20B.html
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/4b6f269a-9cd1-4160-960e-a68e6d46f2b3)

**Comment by LuigiP57** [comment]
#1979 
Perhaps this munition could be added to the PCH-191 to increase its combat capability? Like the PrSM with anti-ship capability? Because almost all available information shows that the DF-12/M20B and FD480/BRE10 are almost the same thing.
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/a8b52341-d27d-4dd2-8259-6da2d1a4d098)

**Comment by PygmalionOfCyprus** [comment]
Was added in 508.

**Comment by PygmalionOfCyprus** [comment]
I wonder if this is actually intended for the PLAGF...it seems more targeted towards export customers, especially since it uses the M20 (export) designation. I think the PLAN generally handles most of the coastal defense taskings for the PLA, doesn't it? (Of course the PLARF also has AShMs.) Relatively short-range coastal defense weapons for the PLAGF seems unusual.

I've added the weapon and WRs but I'm not adding it as a PLAGF weapon until we get an indication that the AShM version is actually in service, or we see an export customer to add it for instead.
