### ISSUE TITLE
Patriot CEC Issue

### ISSUE THREAD

**Issue by Fir3w411** [PygmalionOfCyprus/cmo-db-requests#4061]
### DB Selector

DB3K

### Affected DBID(s)

3546, all other Patriot batteries too

### Description of Problem

Attempting to link any of the Patriot batteries in CMO to CEC platforms is impossible. 

See this forum post for further information:

https://www.matrixgames.com/forums/viewtopic.php?f=10230&t=400332

### Recommended Fix

The Patriot battery needs CEC capability.

**Comment by PygmalionOfCyprus** [comment]
Okay, this one's a little tricky.

Because of the gross way that comms work right now (pre-simside overhaul), enabling something like "CEC for Patriots" isn't as easy as just slapping in a comms link and calling it a day. If Patriot was documented as being linked to CEC, then I would, but because you're basically trying to create a custom network, I can't just toss in comms connections willy-nilly to suit this specific use case.

A better solution for this would be to put in a request for a new comms/network type that achieves what you're trying to do. For example, request IBCS, gimme a list of the platforms it should talk to, etc.
