### ISSUE TITLE
United States, SM-6 Block 1B, range issue

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4174]
### DB Selector

DB3K

### Affected DBID(s)

weapon 3714 3772

### Description of Problem

Their maximum range was inexplicably changed to 1325nm. Did you accidentally copy the SM-3 NTW Block 2A's range data?

### Recommended Fix

Reduce it to 230nm as other SM-6 missiles.

**Comment by TempestII** [comment]
The question came up the CMO Discord too as a few of us were sceptical. Apparently the Blk 1B will use as SM-3 motor which gives it a much longer range than the Blk 1A. Where the 1325nm figure came from I have no idea though, and it might only be for land, sea, and/or incoming projectiles rather than aircraft. It's difficult to know from the sources I can find, which aren't many. 

https://breakingdefense.com/2020/11/army-picks-tomahawk-sm-6-for-mid-range-missiles/

https://www.cbo.gov/publication/58924

"Option 5: Short-Range, Ground- or Sea-Launched Ballistic Missiles (Similar to SM-6 Block IB)
Under Option 5, the Army and the Navy would deploy the Standard Missile-6 Block IB, which the Navy is in the process of developing. The Block IB is a variant of the Navy’s existing SM-6 Block IA, a short-range, supersonic guided missile that can be used for air defense, missile defense, and antiship warfare. Reports indicate that the Army is also interesting in fielding the Block IB missile.

The new missile is a significant modification of the Block IA version, with a range that may be as long as 1,000 km and an average speed in the low hypersonic regime (Mach 5 to Mach 6). That range and speed require the development of a new, larger booster as well as enhanced sensor technology. The SM-6 Block IB missile would be used for attacking surface targets and would be powered by a two-stage rocket booster. The SM-6 Block IB is not a hypersonic boost-glide missile, because it would fly a modified ballistic trajectory and would not use the air to produce lift.

To provide a direct comparison with the other options, CBO assumed that the Army and the Navy would purchase a combined total of 300 SM-6 Block IB missiles under this option, plus ground equipment for six Army batteries. The Army’s missiles could be fired from modified ground-launch vehicles. The Navy’s missiles could be fired from the same large tubes on Zumwalt class destroyers and Virginia class submarines as the IR-CPS missiles in Option 1. The Block IB missiles would also be compatible with the MK 41 vertical launchers on cruisers and Arleigh Burke class destroyers, greatly increasing the number of ships that could carry them. For that reason, it is possible that more SM-6 Block IB missiles would be purchased."

It does seem as though the SM-6 Blk 1B's entry into service date is too early with the above sources.

**Comment by LuigiP57** [comment]
Based on this statement of your second link, we are still not sure that the SM-6 Block-IB is the so-called "< 1000km" missile. Perhaps we can suggest to DB manager to add a new missile of this type.

I speculate that DB manager may not have originally intended to change the range of the Block-IB. Perhaps we can give the SSM version a more reasonable longer range than the SAM version.

**Comment by PygmalionOfCyprus** [comment]
I am sure that the SM-6 Block IB is the "1000km missile," and if you don't believe me, take it up with the Congressional Budget Office.

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/87087226/9672bd4a-a41c-4574-b9f2-504c473a6e2f)

[The Drive also reports](https://www.thedrive.com/the-war-zone/27068/navy-to-supersize-its-ultra-versatile-sm-6-missile-for-even-longer-range-and-higher-speed) that the 1B is the missile getting the "new" (well, recycled from SM-3) 21-inch motor.

With that said, while I did not "inexplicably" and "accidentally" change the range, I did make a mistake. In pulling the range from the 21-inch-motor-equipped SM-3 and applying it to the SM-6 Blk IB, I forgot that the new SM-3s _also_ get a third-stage rocket motor, which helps push them out to those super-long-ranges. Basically, I gave the SM-6 Blk IB an extra stage. Whoops.

Specific range numbers are nonexistent, but given that the CBO calls it a <1000km (540nmi) missile, applying the same standard I do for vague numbers would put it at about 500nmi (bleck, I hate guessing). That seems fair, and much more reasonable than the 1325nmi number I plucked from the SM-3. 

I also agree that the missile in its SSM capability will have a longer practical range than as a SAM (although this gets real icky real quick, because you could probably _technically_ reach out and touch a non-maneuvering aircraft at extreme ranges...). 

And yes, the IS date is way early. Not sure why it says 2017...OSD estimates more like 2027.

Handled 505.

**Comment by LuigiP57** [comment]
> Why do you think the Blk IB is not the missile mentioned? Every single source I've found explicitly describes the SM-6 Block IB as being the missile we're discussing; the CBO report mentions it by name (in this context "similar to" implies that the Blk IB is a representative example).
> 
> The SSM and SAM versions are also the same thing. The SM-6 Block IB was developed primarily as a hypersonic anti-ship missile, and so will have a larger warhead, etc. to support that mission, but it retains its SAM lineage and so can still presumably be used to that purpose. Not sure which "SAM version" you're referring to; the other SM-6 ranges are all mostly in line with consensus.

![IMG_20240124_133315_edit_40679876416188](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/e0c528bb-7495-4fe5-ab50-a1773356ff06)

Here's a screenshot from a certain slide show from the Surface Warfare Division. It is clear that SM-6 Blk IB only has ASuW function, so this may prove in a sense that SM-6 Blk IB does not have a corresponding SAM version. You should be right. SM-6 Blk IB should have a high probability of AShM only.

**Comment by PygmalionOfCyprus** [comment]
One thing to note about that slide is that it's apparently indicating primary missions, not capabilities. For example, RAM does have a documented anti-surface capability, it's just not a primary mission of the missile.

**Comment by KJohnston11** [comment]
> > Why do you think the Blk IB is not the missile mentioned? Every single source I've found explicitly describes the SM-6 Block IB as being the missile we're discussing; the CBO report mentions it by name (in this context "similar to" implies that the Blk IB is a representative example).
> > The SSM and SAM versions are also the same thing. The SM-6 Block IB was developed primarily as a hypersonic anti-ship missile, and so will have a larger warhead, etc. to support that mission, but it retains its SAM lineage and so can still presumably be used to that purpose. Not sure which "SAM version" you're referring to; the other SM-6 ranges are all mostly in line with consensus.
> 
> ![IMG_20240124_133315_edit_40679876416188](https://private-user-images.githubusercontent.com/107970049/299195702-e0c528bb-7495-4fe5-ab50-a1773356ff06.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxOTQyNTEsIm5iZiI6MTcwNjE5Mzk1MSwicGF0aCI6Ii8xMDc5NzAwNDkvMjk5MTk1NzAyLWUwYzUyOGJiLTc0OTUtNGZlNS1hYjUwLWExNzczMzU2ZmYwNi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNVQxNDQ1NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYTkzZDc1MjA2ODJhOGE4YzU2NGU0NTljNDk5ZTFjOTcwNjUxYWRlMmMwZTAyOTJkMmFlMWNmMTZhNDllYWMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QMEqvkAgEw9D-JxqipIvDMVKz2wDmc453JBwW4DglJ4)
> 
> Here's a screenshot from a certain slide show from the Surface Warfare Division. It is clear that SM-6 Blk IB only has ASuW function, so this may prove in a sense that SM-6 Blk IB does not have a corresponding SAM version. You should be right. SM-6 Blk IB should have a high probability of AShM only.

SM-6 Block IB is not exclusively ASuW, several graphics have this from earlier in development. It retains AAW and ASuW capability. 

> The Navy upgraded the Block I and Block IA missiles to provide additional anti-surface capability through the Navy’s FCD mission set expansion effort. Block IB is a modification of the Block IA missile that the Navy intends to extend engagement range through development of a new second stage rocket motor. 

https://www.dote.osd.mil/Portals/97/pub/reports/FY2022/navy/2022sm-6.pdf?ver=JtGbsvvWg8elnI6fT6_n3g%3D%3D

> The Defense Department has launched a prototype project that aims to dramatically increase the speed and range of the Navy’s Standard Missile-6 by adding a larger rocket motor to the ship-launched weapon, a move that aims to improve both the offensive and defensive reach of the Raytheon-built system.

https://crsreports.congress.gov/product/pdf/RL/RL33745/222

**Comment by FIM43-Redeye** [comment]
> The SM-6 Block IB was developed primarily as a hypersonic anti-ship missile, and so will have a larger warhead, etc. to support that mission,

This would help a lot with using it as such, but the SM-6 currently has warhead 849, the ABM-optimized frag of the RIM-156B. Is this intended or should I go looking for data on the new warhead to submit?

**Comment by KJohnston11** [comment]
> > The SM-6 Block IB was developed primarily as a hypersonic anti-ship missile, and so will have a larger warhead, etc. to support that mission,
> 
> This would help a lot with using it as such, but the SM-6 currently has warhead 849, the ABM-optimized frag of the RIM-156B. Is this intended or should I go looking for data on the new warhead to submit?

I don't think it has a new warhead, it's a modification of the SM-6 Block IA

**Comment by PygmalionOfCyprus** [comment]
While little is known for sure about the IB, the general pulse seems to imply that it is in fact getting a more ASW-appropriate warhead. [Here's AviationWeek](https://aviationweek.com/defense-space/missile-defense-weapons/document-likely-shows-sm-6-hypersonic-speed-anti-surface-role), citing USN docs:

>“Additional work for guidance and control **as well as warhead design** will yield a new capability that provides antiair-warfare capability, including cruise missile defense, in support of ships [sic] self-defense, as well as anti-surface warfare,” Guerts’ testimony states.

This meshes with common sense. Since the variant was developed primarily for use in anti-surface roles, it seems unlikely that they'd retain the ABM-optimized warhead.

(Incidentally, this also proves our points above re: retained AAW capability.)

@FIM43-Redeye, you're welcome to hunt, but good luck finding anything concrete about this program. I think we'll just have to guess at it. My money is on kinetic: at hypersonic speeds you don't really need the extra ~65kg of explosives, and SM-3 uses a kinetic kill vehicle already.
