### ISSUE TITLE
SM-6 Blk IB 

### ISSUE THREAD

**Issue by HunterDNiu** [PygmalionOfCyprus/cmo-db-requests#4196]
Add seekers: sensor 4062, 6436.
Add ground search to sensor 5947.
[https://www.thedrive.com/the-war-zone/27068/navy-to-supersize-its-ultra-versatile-sm-6-missile-for-even-longer-range-and-higher-speed](url)

Also, Army MRC capability requires land strike capability. The current MRC SM-6 cannot effect damage to ground targets.

**Comment by PygmalionOfCyprus** [comment]
The bits about the extra seekers were speculation from Tyler; [the Army has since confirmed that it is not modifying the Navy's missiles](https://breakingdefense.com/2020/11/army-picks-tomahawk-sm-6-for-mid-range-missiles/), so extra seekers aren't happening for now.

>I asked the Army if it would modify either weapon to better its needs: The answer is no. “The Army will not modify the Navy missiles,” an official said in an email to Breaking Defense. That means the Army’s going to buy exactly what the Navy is getting.

I've half a mind to deprecate the distinct MRC Blk IB entry in light of this. Interestingly, this implies that the Navy's IBs will also have a land-attack capability.
