### ISSUE TITLE
Reduce PL-15 Missile rocket Operation Time

### ISSUE THREAD

**Issue by clerara10** [PygmalionOfCyprus/cmo-db-requests#4272]
### DB Selector

DB3K

### Affected DBID(s)

CH-AA-10 Abaddon [PL-15] (2018+)

### Summary of Changes

The current PL-15 rocket runs for about 80 seconds
The AIM-120D with the same dual-pulsed solid propellant rocket motor has an engine running time of about 40 seconds and the meteor with Ramjet doped Rockets has an operating time of 50 seconds.

The PL-15 isn't much bigger than the meteor, and the Dual Pulsed Rocket Motor doesn't last longer than the Ramjet Ducted Rocket, so the PL-15's 80-second combustion time is thought to be too long.

In fact, meteor's Ramjet Dutted Rocket is considered superior to the traditional Dual Pulsed Rocket, and considering that the PL-15 uses more fuel by flying at 2900knt, the rocket's operating time should change.

Therefore, the rocket operating time of PL-15 must be modified between AIM-120D and Meteor.

### Sources

https://en.wikipedia.org/wiki/Meteor_(missile)

https://en.wikipedia.org/wiki/PL-15

https://www.iiss.org/online-analysis//military-balance/2022/09/analysis-air-to-air-warfare-speed-kills

https://www.quora.com/Which-BVR-missile-is-better-Meteor-or-PL-15

**Comment by LuigiP57** [comment]
Hey, buddy. You may not know this, but I'm working on some changes to the fuel time and endurance of the air-to-air missiles in this game. But it was so much work that I had to revise it one by one.

But since you brought it up, I'm going to open an issue later today where I'll explain my thinking and some of the air-to-air and surface-to-air missile models that I've modified.

**Comment by tksfpj** [comment]
> Hey, buddy. You may not know this, but I'm working on some changes to the fuel time and endurance of the air-to-air missiles in this game. But it was so much work that I had to revise it one by one.
> 
> But since you brought it up, I'm going to open an issue later today where I'll explain my thinking and some of the air-to-air and surface-to-air missile models that I've modified.

I know that the current game's air-to-air missile system is not complete yet, but I still don't think the PL-15's fuel time is too long to fit into a system that will change So I open this issue. Thank you for your response 😀

**Comment by ddranidis** [comment]
> I know that the current game's air-to-air missile system is not complete yet

Really? That would be news to the dev team that put it together and refined it.

**Comment by PygmalionOfCyprus** [comment]
Closed as per conversation in #4276. Unless we have a specific burnout time we're not in the business of fiddling with the numbers DB-side; this is more of a sim-side thing. (With that said I do think changes since this was posted have made things a bit more logical: Meteor's ramjet is now tagged as a distinct propulsion type, while the AIM-120D and PL-15 are now both using the same "long-burn" rocket propulsion to model their dual-pulse motors.)
