### ISSUE TITLE
Air-to-Air missile, fuel burn time & endurance & max range

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4276]
### DB Selector

DB3K

### Affected DBID(s)

List below

### Summary of Changes

**This is a ticket that is constantly updated. If there is no special reason, I hope the DB manager does not close it.**

Since the CMO updated the air-to-air and surface-to-air missile flight performance, I have found that the actual maximum range of the weapon has little to do with the maximum range described in DB general data.

According to my observation, the maximum range and NEZ of the missile depend entirely on the following four indicators: missile acceleration from 0 to top speed, missile top speed, fuel burn time and endurance.

At present, the combination of these values gives the missile a maximum range and dynamic range that are difficult to estimate. I know it's hard for the dev and DB teams to fully refine this. However, we can at least make these values conform to the maximum range described in general data in the current situation, and make their performance "a little" realistic.

Here's what I found (Take the aim-120c-8 as an example): 

All the air-to-air missiles I've tested have gone from zero to top speed in 5 seconds, which is the missile's fuel burn time. The AIM-120C-8 has a fuel burn time of 38 seconds and a full top speed time of 33 seconds. Its unpowered glide time is 116 seconds, from top speed to complete stop.

Therefore, we can calculate the actual maximum range of the AIM-120C-8: 33*2650/3600+(5+116)*2650/3600/2 ≈ 68.8264nm, and the fuel range/NEZ ≈ 26.13nm

**The formula is:**

**1. AAM's max range ≈ A x B/3600+ (C+D) x B/3600/2**

**2. fuel range/NEZ ≈ A x B/3600+C x B/3600/2**

A is the max speed duration
B is for max speed
C is the acceleration time
D is the endurance time of unpowered gliding

Accordingly, based on current DB max speed and max range, I propose modifications to the following missiles:

- [ ] CH-AA-10 Abaddon [PL-15] - weapon 3413: fuel time - 60s (8 inch diameter allows it to carry more fuel); endurance - 154s
- [ ] CH-AA-10 Abaddon [PL-15E] - weapon 3896: fuel time - 40s; endurance - 120s
- [ ] AIM-260 JATM - weapon 3567: fuel time - 65s (8 inch diameter speculate); endurance - 201s
- [ ] AIM-120D AMRAAM P3I.4 - weapon 51: fuel time - 30s (current C7*150%, same motor, 7 inch diameter); endurance - 180s
- [ ] AIM-120D-3 AMRAAM F3R - weapon 4290: fuel time - 50s (7 inch diameter); endurance - 163s
- [ ] Meteor family - weapon 371, 961, 4106: fuel time - 80s (ramjet should have longer fuel range, 7 inch diameter); endurance - 117s (its aerodynamic shape causes it to decelerate significantly)
- [ ] AAM-4B [Type 99 Mod] - weapon 1199: fuel time - 30s (current AAM-4*150%); endurance - 132s
- [ ] AA-12 Adder C [R-77M] - weapon 3126: fuel time - 50s; endurance - 133s

### Sources

Game itself

**Comment by LuigiP57** [comment]
#4272

**Comment by ddranidis** [comment]
As we have repeatedly explained (example: https://www.matrixgames.com/forums/viewtopic.php?p=5068024#p5068024), the burn times in boost-coast weapons are not pre-stored in the DB, but instead dynamically calculated the first time that a weapon is about to be used (or the first time it is displayed in the DB viewer).

Also, the formula referenced in this request is very simplistic (it assumes a constant-altitude, no-turn boost + coast profile) and does not account for the actual trajectory of the weapon during its DLZ simulated flyout, and the numerous factors affecting _actual_ (not nominal) weapon speed and range.

Furthermore, the "endurance" figure displayed on the DB viewer is itself dynamically calculated (as with the boost-burn time, it starts with the assumption that the weapon is indeed able to make the intercept under certain nominal conditions, and works "backwards"), and explicitly lasts slightly longer than the nominal weapon max range. A missile may have e.g. a 80nm nominal range, but be able to fly out to 90-95nm and hit something. This is by design.

People who work on these things for a living have gone over our model, assumptions and abstractions and come away very satisfied with them. We are very sorry if it doesn't meet your high standards.

**Comment by LuigiP57** [comment]
> As we have repeatedly explained (example: https://www.matrixgames.com/forums/viewtopic.php?p=5068024#p5068024), the burn times in boost-coast weapons are not pre-stored in the DB, but instead dynamically calculated the first time that a weapon is about to be used (or the first time it is displayed in the DB viewer).
> 
> Also, the formula referenced in this request is very simplistic (it assumes a constant-altitude, no-turn boost + coast profile) and does not account for the actual trajectory of the weapon during its DLZ simulated flyout, and the numerous factors affecting _actual_ (not nominal) weapon speed and range.
> 
> Furthermore, the "endurance" figure displayed on the DB viewer is itself dynamically calculated (as with the boost-burn time, it starts with the assumption that the weapon is indeed able to make the intercept under certain nominal conditions, and works "backwards"), and explicitly lasts slightly longer than the nominal weapon max range. A missile may have e.g. a 80nm nominal range, but be able to fly out to 90-95nm and hit something. This is by design.
> 
> People who work on these things for a living have gone over our model, assumptions and abstractions and come away very satisfied with them. We are very sorry that it doesn't meet your high standards.

Got it

**Comment by PygmalionOfCyprus** [comment]
I will note that we do actually have an in-DB override for burnout time when these values are actually known. If you can find data on burnout times for specific motors/missiles then by all means let us know and we can tweak these specific weapon entries accordingly.

That said, general ticket closed for above reasons.
