### ISSUE TITLE
Current sensors in DB with two operating band in one mode, this cut detecting range

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4277]
### DB Selector

DB3K

### Affected DBID(s)

List below

### Summary of Changes

**This is a ticket that is constantly updated. If there is no special reason, I hope the DB manager does not close it.**

- [ ] Long Mountain - sensor 6366: change to G
- [ ] YLC 2V/6/6M/8B/8E - sensor 2513 5441 5442 5571 7109: For 2513 5441 5442 change to F, for 5571 7109 cahnge to B
- [ ] SLC-18 - sensor 6992: change to A
- [ ] JY-14 - sensor 2621: change to E
- [ ] JY-26 - sensor 5570: change to B
- [ ] SR2410C - sensor 6542: change to F
- [ ] China Type XXX X-Band Radar - sensor 7279: change to I

### Sources

No need

**Comment by claudejdev** [comment]
You mean there is a bug or something with multiple operating bands?

**Comment by LuigiP57** [comment]
> You mean there is a bug or something with multiple operating bands?

Indeed

**Comment by claudejdev** [comment]
Does it have been reported to the devs, on the forum, already?

**Comment by PygmalionOfCyprus** [comment]
I think this is a bug to report on the forum rather than a DB change _except_ in cases where the sensors are erroneously marked as having two bands. There are sensors which really do operate in multiple bands and I don't want to remove this data just because something weird is happening sim-side.

That said, if there are sensors with the wrong frequency data, feel free to report as normal.
