### ISSUE TITLE
Status-6 torpedo unusable

### ISSUE THREAD

**Issue by Siegemiester** [PygmalionOfCyprus/cmo-db-requests#4332]
### DB Selector

DB3K

### Affected DBID(s)

3473

### Description of Problem

This torpedo can only target ground units and lacks BOL capability. Even if used against a ground unit, torpedo will fail to hit the target due it being a torpedo and can't move onto land.

### Recommended Fix

Add BOL capability as it's intended to be detonated offshore against onshore targets

**Comment by PygmalionOfCyprus** [comment]
It's sort of a weird weapon that doesn't play well with how the sim expects torpedoes to work. Added BOL, and also gave it the ability to shoot at surface contacts -- not because this is an expected use case, but so you can add a surface "target" (e.g. a marker) to shoot at if this is a scenario objective. Best I can do DB-side. Hanlded 505.
