### ISSUE TITLE
J20 issues

### ISSUE THREAD

**Issue by Siegemiester** [PygmalionOfCyprus/cmo-db-requests#4335]
### DB Selector

DB3K

### Affected DBID(s)

2463, 5454, 5014, 5012, 5013

### Summary of Changes

*Based on OSINT RCS Scattering the J20 should roughly be only a few times larger than the F35, even accounting for differences in RAM, it should be maybe 20x larger Not 280x in RCS.  
https://basicsaboutaerodynamicsandavionics.wordpress.com/2022/11/27/j-20-radar-scattering-simulation/

*The twin seat J20S is likely to be used as an electronic warfare platform, it should be given access to OECM pods of its equal era (at least late 2010s)

*Its been stated the J20 with WS10C engines can achieve limited supercruise, meaning at military speed it should be able to go at minimum above Mach 1

*The general consensus is the J20 has a maximum design speed of Mach 2. The J20B with WS15s should be able to achieve this speed with afterburners, especially since it has internal stores so its by default in a clean configuration

*The WS15 is a considerably more advance engine than all WS10 Variants. This should mean the J20B WS15 should have a noticeably increased combat radius.

### Sources

https://en.wikipedia.org/wiki/Chengdu_J-20

https://basicsaboutaerodynamicsandavionics.wordpress.com/2022/11/27/j-20-radar-scattering-simulation/

**Comment by LuigiP57** [comment]
> *The twin seat J20S is likely to be used as an electronic warfare platform, it should be given access to OECM pods of its equal era (at least late 2010s)

It is good to see that more people are willing to clear the name of the J-20. However, when we make assumptions, we must not be too detached from reality. I don't see any solid OSINT evidence to support this claim. Can you provide any sources to support this claim? But it's better not to have a War Thunder Forum like leak.

**Comment by Siegemiester** [comment]
> > *The twin seat J20S is likely to be used as an electronic warfare platform, it should be given access to OECM pods of its equal era (at least late 2010s)
> 
> It is good to see that more people are willing to clear the name of the J-20. However, when we make assumptions, we must not be too detached from reality. I don't see any solid OSINT evidence to support this claim. Can you provide any sources to support this claim? But it's better not to have a War Thunder Forum like leak.

Since the J20S ingame is already a hypothetical unit, Any takes on its role and performance are purely speculative, 
https://nationalinterest.org/blog/buzz/flying-tandem-inside-china%E2%80%99s-two-seat-j-20-stealth-fighter-205182
But based off 'expert opinion' Electronic warfare is a likely role 

I'm just pitching this addition because so far in game the J20S is totally redundant.

**Comment by PygmalionOfCyprus** [comment]
Thank you for the ticket! We'll review this next cycle when we do our PLAAF review.

In the future, please try to preface the Affected DBIDs / Baseline to Copy section with the relevant annex (e.g., in this case, "Aircraft 2463, 5454, 5014, 5012, 5013" so the Github bot can auto-classify the ticket.

**Comment by LuigiP57** [comment]
> > > *The twin seat J20S is likely to be used as an electronic warfare platform, it should be given access to OECM pods of its equal era (at least late 2010s)
> > 
> > 
> > It is good to see that more people are willing to clear the name of the J-20. However, when we make assumptions, we must not be too detached from reality. I don't see any solid OSINT evidence to support this claim. Can you provide any sources to support this claim? But it's better not to have a War Thunder Forum like leak.
> 
> Since the J20S ingame is already a hypothetical unit, Any takes on its role and performance are purely speculative, https://nationalinterest.org/blog/buzz/flying-tandem-inside-china%E2%80%99s-two-seat-j-20-stealth-fighter-205182 But based off 'expert opinion' Electronic warfare is a likely role
> 
> I'm just pitching this addition because so far in game the J20S is totally redundant.

Maybe, an OECM capability generated by an AESA radar could be more reasonable, like the F-35's APG-81 OECM? EW capability may also mean SIGNT capability.

**Comment by Siegemiester** [comment]
> > > > *The twin seat J20S is likely to be used as an electronic warfare platform, it should be given access to OECM pods of its equal era (at least late 2010s)
> > > 
> > > 
> > > It is good to see that more people are willing to clear the name of the J-20. However, when we make assumptions, we must not be too detached from reality. I don't see any solid OSINT evidence to support this claim. Can you provide any sources to support this claim? But it's better not to have a War Thunder Forum like leak.
> > 
> > 
> > Since the J20S ingame is already a hypothetical unit, Any takes on its role and performance are purely speculative, https://nationalinterest.org/blog/buzz/flying-tandem-inside-china%E2%80%99s-two-seat-j-20-stealth-fighter-205182 But based off 'expert opinion' Electronic warfare is a likely role
> > I'm just pitching this addition because so far in game the J20S is totally redundant.
> 
> Maybe, an OECM capability generated by an AESA radar could be more reasonable, like the F-35's APG-81 OECM? EW capability may also mean SIGNT capability.

Possible but I can't find any literiture or even suggestions the 1475 (KLJ-5) can do electronic attack. Whereas dedicated ECM pods (which would explain why a second pilot is needed) would be able to do that for sure.

Also. if we assume the 1475 (KLJ-5) can jam then ALL J20 variants would end up having that ability which wouldn't make a ton of sense to build an entirely new variant in the first place.

Also yes, its possible the J20S could play as some sort of ELINT/SIGNIT aircraft since it's stealthy enough to do that quite well.

**Comment by Test229** [comment]
*The general consensus is the J20 has a maximum design speed of Mach 2. The J20B with WS15s should be able to achieve this speed with afterburners, especially since it has internal stores so its by default in a clean configuration

I think there was a reason why some stealth fighters don't get ab in the game. (F-22, Su-57 and J-20) Don't remember what that was exactly

**Comment by PygmalionOfCyprus** [comment]
Most of this has been handled during our PLAAF review, so closing. I'm also curious to see what, if anything, becomes of the two-seater J-20. It might be an Occam's razor situation where it's just a trainer, but I personally think it's more likely going to serve as a MUM-T platform or something. That's what a lot of the Chinese domestic speculation points to.

**Comment by PygmalionOfCyprus** [comment]
Also, as an aside, random Wordpress blogs and engineering students faffing about with CAD models are not reputable sources for stealth signatures -- I all but ignored them for info on the F-22/F-35 and I intend to do the same for the J-20, FC-31, etc. Unless they are secretly leaking info out of China they do not have the information they need to give anything resembling an accurate simulation. They don't know about RAM quality, microtexturing, active cancellation, internal RCSS, the subtle tiny changes of aircraft skin (e.g. rivet quality) that cannot be represented in a hobbyist model, etc. This stuff gets simulated by supercomputers.

Most serious experts and Chinese doctrinal statements generally seem to agree that the J-20 is more of a...4.75 gen stealth aircraft, if you will. Stealthy, to be sure, and a foe to be feared by anyone in a 4.5 gen or lower, but the (US, not export) F-35s and F-22s are really in a league of their own. I won't pretend to know if the numbers we give are anywhere near accurate, but we've gotten good feedback from pro clients. Do with that information what you will.

There's a reason we don't get sucked into specific RCS values and instead just use a series of "modifiers" to classify things by general stealth era/qualities. No one knows, except the pros. (That's why they can modify RCS values in CPE. :P)

**Comment by LuigiP57** [comment]
> Most serious experts and Chinese doctrinal statements generally seem to agree that the J-20 is more of a...4.75 gen stealth aircraft, if you will.

I wonder if these "serious experts" are also the same people who have asserted countless times that Russia has run out of ammunition and been easily defeated by Ukrainian and NATO equipment.

Of course, I'm more interested in what you call "Chinese doctrinal statements". Can I see?

**Comment by LuigiP57** [comment]
@PygmalionOfCyprus Also, are you going to fix the low **side RCS** of stealth fighters in the game? Whether it is F-22, F-35 or J-20, Su-57, Kaan, KF-21, there are a large number of non-parallel reflectors on the side of the body.

If doubt my claim, you can consult a professional you trust.

**Comment by Siegemiester** [comment]
Somehow I find it hard to believe china hasn't figured out technology thats 20+ years old despite having successfully breached Both Lockheed Martin and Boeing for their stealth secrets over 15 years ago.

Stealth coatings and airframe construction is probably the easiest part of a 5th generation fighter to replicate since it doesn't involve moving parts, extreme precision engineering or electronic/software wizardy. 

And lets not forget china has Literally captured wreckage of the F117 from all the way back in Yugoslav war. And yet the F117 still has a smaller RCS than any chinese manned fighter in game, Are we to assume that china in 2024 cannot replicate stealth materials of something made in the late 80s, designed with computers that have less processing power than a modern smartphone with non of the fancy active cancellation or internal RCSS, despite having a physical hard copy? Stealth tech isn't magic. It doesn't stop working the moment non-Americans try to reproduce it.

**Comment by Siegemiester** [comment]
> > Most serious experts and Chinese doctrinal statements generally seem to agree that the J-20 is more of a...4.75 gen stealth aircraft, if you will.
> 
> I wonder if these "serious experts" are also the same people who have asserted countless times that Russia has run out of ammunition and been easily defeated by Ukrainian and NATO equipment.
> 
> Of course, I'm more interested in what you call "Chinese doctrinal statements". Can I see?

Strictly speaking the chinese consider the J20 a 4th gen fighter because china's 1st gen jet fighter was a mig15 which is considered 2nd gen.


Sure. The prototype J20s like the ones shown in 2011 could be considered 4.75gen. They lacked proper engines, Stealth coatings, EOTS and long range AAMs like the PL15. That I can agree with. But calling a contemprary J20 with WS15 engines, EOTS and refined external stealth features 4.75gen does sound disingenuous 

Maybe you could keep the poorer stealth features for the early models of J20 while giving it a smaller RCS for later models such as the J20B ect.  I know this is being done for F35s in game currently.

**Comment by Siegemiester** [comment]
> Also, as an aside, random Wordpress blogs and engineering students faffing about with CAD models are not reputable sources for stealth signatures -- I all but ignored them for info on the F-22/F-35 and I intend to do the same for the J-20, FC-31, etc. Unless they are secretly leaking info out of China they do not have the information they need to give anything resembling an accurate simulation. They don't know about RAM quality, microtexturing, active cancellation, internal RCSS, the subtle tiny changes of aircraft skin (e.g. rivet quality) that cannot be represented in a hobbyist model, etc. This stuff gets simulated by supercomputers.
> 
> Most serious experts and Chinese doctrinal statements generally seem to agree that the J-20 is more of a...4.75 gen stealth aircraft, if you will. Stealthy, to be sure, and a foe to be feared by anyone in a 4.5 gen or lower, but the (US, not export) F-35s and F-22s are really in a league of their own. I won't pretend to know if the numbers we give are anywhere near accurate, but we've gotten good feedback from pro clients. Do with that information what you will.
> 
> There's a reason we don't get sucked into specific RCS values and instead just use a series of "modifiers" to classify things by general stealth era/qualities. No one knows, except the pros. (That's why they can modify RCS values in CPE. :P)


Without getting Overly technical
https://arstechnica.com/information-technology/2015/11/chinese-scientists-develop-radar-absorbing-active-stealth-material/
The article alone says chinese RAM could reduce RCS by between 10-40db depending on wavelength.

https://file.scirp.org/pdf/EPE20110400019_14389867.pdf
And an Actual scientific paper produced by china for RAM from 2011. Showing that materials that could reduce radar returns by well over 30db were studied. All this before the first J20 publicly flew.

Chinese progress in RAM is definately not so primative that Fighters made in the 2020s can't compete with something like the F117 for stealthiness

**Comment by PygmalionOfCyprus** [comment]
My initial comment was more aimed at the value of "this guy ran a simulation and says X" sources, not a statement that I will never consider changes to the J-20 or any other stealth aircraft's RCS values.

That said, I do find these sorts of discussions -- when people show up saying "the RCS should be decreased by X dB," etc. -- tiresome, because ultimately none of us have any idea what we're talking about. We're making best guesses about where planes are in relation to each other on the nebulous "stealth chart" based on random tidbits of info and anecdotes. Great, there's a paper that says a specific type of Chinese RAM at a certain university reduced RCS by 30 dB in a certain test. Is that the same kind of RAM on the J-20? How is it applied? What other components of the airframe affect it? Etc. etc.

People will never be happy, because everyone's mental "stealth chart" is different. The Sinoboos want the J-20 -- a first-of-its-kind stealth aircraft from a country that still struggles to make a reliable jet engine -- to be as good if not better than an F-35, a now 3rd-gen stealth fighter featuring first-in-the-world stealth tech like active cancellation, etc. (that we _know of_) because China Daily told them it was. The vatniks want the Su-57 to be at least as good as the F-22 because...I dunno, it looks vaguely stealthy, I guess. And of course the Ameritards want the F-35 to be literally invisible to everything and get mad when it even shows up on radar.

Command is not a J-20 simulator, it's a detailed abstraction. We only need to land at "good enough." At a certain point we just need to get it into the ballpark and accept that the truth is beyond our clearance levels and our paygrade.

_That said_, I'm not ideologically opposed to bumping up the J-20's stealth. We may well be out of the ballpark. I think the fact the U.S. are using F-35s as aggressors means something. I do think it's fair to say that they're not so far behind as the DB currently implies.

>Maybe you could keep the poorer stealth features for the early models of J20 while giving it a smaller RCS for later models such as the J20B ect. I know this is being done for F35s in game currently.

This is a good idea. Giving the "Modern Shaping, Lite RAM" modifier to the J-20 was borne of information available in earlier models, where it suffered a lot from the older Russian engines, stealth RAM, etc. It's undeniable that they're more stealthy now than they were.
