### ISSUE TITLE
AVIC 601S Dark Sword

### ISSUE THREAD

**Issue by Siegemiester** [PygmalionOfCyprus/cmo-db-requests#4343]
### DB Selector

DB3K

### Hypothetical

Yes

### Name

AVIC 601-S Dark Sword UCAV

### Country

China

### In Commission

2018

### Length (m)

15

### Wingspan (m)

14

### Height (m)

3?

### Empty Weight (kg)

Less than 13000

### Maximum Takeoff Weight (MTOW) (kg)

15000

### Crew

0

### Propulsion

1x WS13 turbofan (non afterburning)

### Service Ceiling (ft)

45000?

### Military/Afterburner Speed (kt)

666

### Cruise Speed (kt)

480?

### Supercruise

Yes

### Ferry Range (nm)

540x2

### Sensors

1x AESA medium range FCR/Search radar
1x EO/LLTV camera

### Mounts

No mounted weapons

### Loadout Options

4 External Pylons allowing for mounting of 

6x FT-7
2x LS-6-250 + 2x LS-6-50
2x LS-6-250 + 2x PL10 
2x LS-6-250 + 4x AKD-9
2x PL12 + 2x PL10
2x PL15 + 2x PL10
4x CM-502KG 

![dark-sword-image02](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/160735116/ac15e89f-551a-4f8c-838a-807ee86f12bb)

### Comments

A very mysterious airframe that has been floating around online since 2006 with almost no concrete information given.

![1529341933_an-czyan-1](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/160735116/1b9f0c7e-81b3-4246-a43a-15d0658256eb)

From basic analysis, it appears to be a low observable drone with high kinematic performance (agility of 4 or more) but not well optimised for stealth as it relies on external mounts for weapons.
https://www.ainonline.com/aviation-news/defense/2018-06-12/china-reveals-supersonic-ucav

It is assumed that it can achieve at least low supersonic performance based off its aggressive wing sweep, but its poor power to weight ratio (of around that of a B1 bomber) might not permit that with a full combat loadout.

It is also suggested that it might have some air to air combat capabilities as the airframe seems to be optimised for agility. but any radar mounted onboard would have little realestate or power reserve to work with due to the single WS13 engine powering it.

Its is entirely possible it just serves as an advanced target drone designed to train chinese AD and fighter crews against low observable, high agility targets

Others speculate that it could be part of china's own 'loyal wingman' program enabling it to operate in tandem with the twin seat J20S and other platforms.

### Sources

https://en.topwar.ru/143212-proekt-temnyy-mech-tainstvennyy-bpla-iz-kitaya.html
https://en.wikipedia.org/wiki/AVIC_Dark_Sword
https://www.ainonline.com/aviation-news/defense/2018-06-12/china-reveals-supersonic-ucav
https://www.globalsecurity.org/military/world/china/anjian.htm

**Comment by LuigiP57** [comment]
You may need a baseline. Aircraft 5703 (Kizilelma A) will be suitable.

**Comment by PygmalionOfCyprus** [comment]
I'm extremely skeptical that this is the platform we want to model to represent this capability for China. (Yes, I know this is a hypothetical request, but still -- as mentioned previously, we've gotta be a little discerning on hypo entries, otherwise we'll get bogged down adding every single thing that ever gets teased at Zhuhai. In general I'm looking for likely adoption and/or transformative capability.) 

As you say, it's been "around" since 2006 and we've seen no realistic indication that this is anything but a testbed for AVIC. Certainly no indications that this is a capability currently being pursued by the PLA. I think there is some merit in adding a hypo "Loyal Wingman" for China, but I doubt this will be it...it's old now, and newer platforms can make use of more recent developments. Like the FH-97 for example.

As it stands we have this weird testbed that doesn't seem particularly good at anything it might be used for. I'm almost positive this is just being used to experiment with things that then get applied to other projects. (Obviously if we start seeing Dark Swords over the skies of Taiwan I'll take the L, but I'm pretty confident we won't.)

**Comment by Luigi-II** [comment]
In fact, I think the GJ-11 can do the job, including BVR air combat. This platform has a more powerful VLO capability to improve its own survivability and BVR advantages.
