### ISSUE TITLE
Chinese Experimental Railgun Platform

### ISSUE THREAD

**Issue by Siegemiester** [PygmalionOfCyprus/cmo-db-requests#4416]
### DB Selector

DB3K

### Baseline

Type 072III

### Hypothetical

Yes

### Name

Haiyang Shan

### Class

Type 072III

### Country

China

### Service

PLAN

### In Commission

2018

### Number in Service

1

### Length (m)

119.5

### Beam (m)

16.4

### Draft (m)

2.8

### Standard Displacement (t)

7000

### Full Displacement (t)

Same as Type 072III

### Empty Displacement (t)

Same as Type 072III

### Complement

104

### Max Sea State

Same as Type 072III

### Primary Propulsion Type

Diesel

### Propulsion

Same as Type 072III

### Fuel Capacity (kg)

Same as Type 072III

### Flank Speed (kt)

Same as Type 072III

### Range (nm) at Speed (kt)

Same as Type 072III

### Sensors

Same as Type 072III

### Mounts

3 × H/PJ76F twin 37mm
1 x Electromagnetic Railgun

### Aircraft & Docking Facilities

Same as Type 072III

### Comms/Datalinks

Type 072III

### Comments

A chinese Type 072III LST Converted to serve as a test platform for an experimental EM railgun which has been reported to be able to fire at a rate of 120rnd/m
https://www.nextbigfuture.com/2023/12/chinas-navy-researchers-claim-to-have-a-hypersonic-railgun-firing-120-rounds-a-minute.html#:~:text=In%20one%20of%20the%20tests,entire%20railgun%20system%20remained%20intact.

With a muzzle velocity of mach 5.8 and a theoretical maximum range of nearly 200km

it is also indicated that china has developed or is developing a guidance system for railgun accellerated projectiles enabling precision targetting at extreme ranges

https://www.thedefensepost.com/2024/01/26/china-dream-shell-us-navy/?expand_article=1
https://www.eurasiantimes.com/proposed-by-us-navy-in-2012-china-develops-hypersoni/

Though guidance methodology is not explained. it is suspected to use Beidou navigation to obtain precision accuracy.

### Sources

https://en.wikipedia.org/wiki/Chinese_landing_ship_Haiyang_Shan

https://www.twz.com/18119/is-this-chinese-navy-ship-equipped-with-an-experimental-electromagnetic-railgun

https://www.nextbigfuture.com/2023/12/chinas-navy-researchers-claim-to-have-a-hypersonic-railgun-firing-120-rounds-a-minute.html#:~:text=In%20one%20of%20the%20tests,entire%20railgun%20system%20remained%20intact.

**Comment by PygmalionOfCyprus** [comment]
Interestingly, we actually don't have any railguns modelled in Command right now AFAIK. I think it's probably worth adding the code-side support, just for experimentation purposes. As it stands, though, it's almost certain that this is just a scientific exercise and not seriously intended for wide-scale deployment, much like the USN's similar programs about a decade ago.

I've asked the devs about adding support for railgun modelling. If they do, I'll add several of the hypothetical railgun platforms for various countries, including this one. For right now I'm gonna close it, though, since this isn't actionable.
