### ISSUE TITLE
China, PLAN, Type 095 signature level unchanged?

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4422]
### DB Selector

DB3K

### Affected DBID(s)

submarine 676

### Summary of Changes

In #3704 , The signature level change request for this unit has been shown to be complete, but there is no change in the 505 database. Why is that?

Or was it put on hold because of the upcoming submarine sound level upgrade?

### Sources

DB 505

**Comment by PygmalionOfCyprus** [comment]
I'll flag @Jkryos but if I had to hazard a guess I'd say it's because w/ the current DB sub signatures we literally can't make those sorts of distinctions. If we bump up its sound signature it will be the same sig as the newest, most cutting-edge subs -- because there is no difference currently in the DB between the Flight I Virginias and the Flight Vs. So, lesser of two evils: either we don't change it, and it's louder than current-gen subs but also louder than some older current-gen subs; or we change it and now it's much quieter than it should be.

You see why we're preparing to overhaul the sub signature system as soon as we get some breathing room. :P
