### ISSUE TITLE
Add Drugs Smuggler; Sailboat

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#4503]
### DB Selector

DB3K

### DBID to Copy

Ship 2398

### Hypothetical

No

### Name

Smuggler, Drugs, Sailboat

### Country

Smugglers

### Service

Drugs

### In Commission

- present

### Other Changes

They are much slower and deeper in the water, Signatures for RADAR little decreased and max 7 kts to 9(?)

### Sources

https://www.walesonline.co.uk/incoming/gallery/cocaine-found-boat-destined-north-7837468
https://www.ybw.com/news-from-yachting-boating-world/dutch-yacht-cocaine-smugglers-sentenced-22731
https://news.sky.com/story/two-drug-smugglers-arrested-as-yacht-seized-off-cornwall-coast-11443597
https://www.europol.europa.eu/media-press/newsroom/news/boat-raided-brazil-to-europe-hiding-over-half-tonne-of-cocaine-and-narcotic-substances
https://insightcrime.org/news/record-drug-bust-yacht-off-coast-portugal

**Comment by Parel803** [comment]
Maybe the country can be pirates & smugglers?

**Comment by PygmalionOfCyprus** [comment]
I don't think these need a distinct DB entry. They can be adequately simulated with Lua, or just by adding the existing civilian entries to a given side, etc. Not to mention that creating distinct "Drug Smuggler" entries actually kind of removes the challenge of finding them because when you click on the ships you'll be able to see that they belong to side "smuggler" rather than being camouflaged as "civilians".

**Comment by Parel803** [comment]
understood
