### ISSUE TITLE
R-23T [AA-7b Apex] air-to-air missile FUEL QUANTITY

### ISSUE THREAD

**Issue by PavelNovak79** [PygmalionOfCyprus/cmo-db-requests#4523]
### DB Selector

Both

### Affected DBID(s)

weapon 789 in DB3K and 747 in CWDB

### Summary of Changes

Change of fuel quantity from current "1,0 seconds (Flight Endurance: 6 sec)" to "7,0 seconds (Flight Endurance: 21 sec)"

Reasoning:
- the 7,0 seconds is used with R-23R [AA-7a] missile and both missiles shares same body with same engine and fuel. They differ only in guidance head so there is no reason for AA-7b to have less fuel in database in comparison to AA-7a
- technically both missiles (R-23R and R-23T) have also same range in pure kinematic aspect - the AA-7b has issues with its guidance head unable to lock on targets on its maximum kinematic range and thus practical lesser range than SARH AA-7a
- but this should not reduce its performance against receding targets which for which is AA-7b primarily used - reduced fuel reduces its ability in chasing receding targets which makes this variant of missile unuseful
- also in game it is currently marked as all-aspect - I will not challenge it now but I will add that its all-aspect capability is rather theoretical than practical (btw. it was cleared for export sooner than basic R-60 [AA-8a])

### Sources

comparison of AA-7a and AA-7b in current database in game

**Comment by PygmalionOfCyprus** [comment]
This is not a fuel issue, this is an issue with how the sim is handling boost/coast based on DB values. Both missiles have the same fuel in the DB. But since the Apex B has a range of almost 1/3 the A in the DB, it is adjusting the burn times appropriately.

The way to fix this is to give the Apex B the same range as the A but reduce the range of its seeker to accurately reflect this limitation. I have now done so. Handled 507.

**Comment by PavelNovak79** [comment]
Thank you for explanation and all work.
