### ISSUE TITLE
508 [Zhuk Class, Pr.1400M Grif] -- Cuba (Coast Guard), 1974, 4x

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#460]
### DB Selector

DB3K

### Affected DBID(s)

1544 and 3502

### Summary of Changes

DBID #1544 duplicated as 3502 for v492 Cuban Navy updates.

### Sources

DB3K v492

**Comment by PygmalionOfCyprus** [comment]
This is a consequence of an interrupted attempt at copying over the relevant CWDB Cuban stuff to DB3K. We're building a new tool to facilitiate easier copying of entries between databases, which is currently in the final stages of testing. Once that goes "live" I plan to move over all the Cuban stuff in CWDB that should also be in DB3K; at that time, I'll replace these duplicate ships.

I'd like to just flat out delete them, but I can't do that, since I don't want to completely brick any scenarios that have been made using these...

**Comment by tbrandon517** [comment]
For the Zhuk the double could probably just be altered to the Pr.1400 or Pr.1400ME models.

https://www.navypedia.org/ships/cuba/cub_cg_506.htm

**Comment by PygmalionOfCyprus** [comment]
Went with @tbrandon517's suggestion and converted  3502 to a base Zhuk as well as adding a Pr.1400ME; was gonna have to do that eventually anyway.
