### ISSUE TITLE
New PLAAF H-6K loadouts

### ISSUE THREAD

**Issue by FRF311** [PygmalionOfCyprus/cmo-db-requests#4698]
### DB Selector

DB3K

### User(s)

PLAAF H-6K God of War

### Weapons Carried

-4×YJ-83KB(CM-802B)  2×KG-800 OECM pods
-12×LS-6-500 Extended-Range Bombs 2×KG-800 OECM pods
-18×LT-2(LS-500J) LGB 
-6×YJ-1000 LGB 
-12×GB-6(JSOW-ER) 2×KG-800 OECM pods
-6×KD-20(CJ-10A ALCM)
-6×AFK-98A
### Requires Buddy Illumination

Yes

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

The LS-6-500 Extended-Range GPS/INS Bombers are similar to JDAM loadouts on USAF B-52H bombers.
As H-6G can load YJ-83K ASMs,H-6K can load YJ-83KB missles is reasonable.

### Sources

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/167990417/da8065e9-9bd1-47a1-93fe-1d4e1f4a39bb)
CM-802 AGM/ASM
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/167990417/ac8ad61b-6ab3-47db-8bd4-a2b23c064791)
GB-1(LT-2) LGB
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/167990417/eeda2077-d1a8-4696-8007-2b233eead917)
GB-5(YJ-1000)LGB
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/167990417/b7be4628-5313-4034-b532-6f8303a1dcc5)
GB-2A Extended-Range Bomb,GPS/INS 500kg HE(LS-6-500)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/167990417/5293a1fc-8abe-417c-ac65-ffaa2611e761)
CS/BBC-5(GB-6)
Those weapons above were all showed on 2016 Zhuhai Air Show.They can all be loaded by H-6K.

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/167990417/3ee864cf-4c66-4b71-8690-688ffa9c8f0a)
https://military.cctv.com/2018/01/27/ARTI9QNDTO9JVB4RmPa4huNk180127.shtml
CCTV article：An electro-optical pod is added under the nose, which gives the aircraft an all-weather target search capability day and night and can provide target indication for satellite-guided or laser-guided bombs.

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/167990417/996df0e1-d55d-452a-8a07-a21a06ca8c6e)
In this CCTV 7 TV program,it showed H-6K use triple mount pylons to load 18 bombs under the airfoil.

H-6K bombers have enough max payload as 13000kg to carry these weapons.

**Comment by PygmalionOfCyprus** [comment]
In the future, please also post an original link/source for the screenshots!

I question whether the H-6K is in fact capable of carrying AShMs like the YJ-83. If it was, what would be the point of the H-6J? When the PLANAF transferred aircraft/responsibility for shore-based ASuW to the PLAAF last year they also transferred the H-6Js. Having never seen an H-6K w/ YJ-83s I believe the H-6Js are (or at least, were) wired for the YJ-83 and the H-6K are not.

I am also not convinced that the appearance of these weapons at Zuhai 2016 means they are actually in service with the PLAAF as armament on the H-6. You'll note that these are all members of the GB family by Norinco. I think this was more just a Norinco exhibit ("look at all our bomb options!") rather than an actual display of weapons in active use. 

This is a pretty notorious problem with trying to figure out bombs for PLA aircraft: there are about a gazillion bombs designed by Chinese state-owned enterprises that get proudly shown off at airshows and as far as we can tell almost none of them are actually in service. Maybe a couple of the lucky ones get exported.
