### ISSUE TITLE
China,PLAAF,J-16 Radar data correction

### ISSUE THREAD

**Issue by yU2187sie** [PygmalionOfCyprus/cmo-db-requests#4699]
### DB Selector

DB3K

### Affected DBID(s)

Sensor 5485

### Summary of Changes

Increase the J-16AESA radar detection range to 200nm
### Sources

In a report on the J-16 in the state-run Global Times, It reads, "the J-16 is a 3.5 generation plane with huge breakthroughs in radar and fire control systems in comparison with previous aircraft ", can we assume that the Chinese have made a welcome breakthrough with the J-16 radar?From public data, we all know that the su-35's Irbis-E radar is 900mm in diameter, while the J-16 has a similar airframe to the su-35. Therefore, in the diameter of the nose radar, the J-16's AESA should be similar to the Irbis-E. Considering that J-16AESA is not Irbis-E combined with mechanical scanning architecture, it is speculated that the radar detection range of J-16 should be between Irbis-E and n036, and the AESA detection range of J-16 should reach the level of 200nm.
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/130222813/f653d8b1-45e6-4ce9-9f80-792c57cb2334)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/130222813/9a300b9d-6f2c-452d-b082-4a1c12ea1845)
In the above picture, some people believe that China's radar technology should not be inferior to Russia's level or even exceed it, although China's radar technology compared to the United States may still be a certain gap.
https://www.globaltimes.cn/page/202103/1219382.shtml
https://militarywatchmagazine.com/article/why-russia-s-air-force-loves-the-su-35-s-irbis-e-radar-a-detailed-look-at-the-sensor-suite-built-to-hunt-stealth-fighters
https://en.wikipedia.org/wiki/Irbis-E

**Comment by PygmalionOfCyprus** [comment]
It's interesting (and frustrating) that as far as I can tell very few sources even try to make a guess at the range of the Chinese AESAs despite having some compelling evidence re: size and T/R modules. Ah, well.

The only place I can find even offering a range for the J-16 AESA is [this terrible source](https://militaryview.com/j-16-vs-su-35-who-is-the-ultimate-flanker/), which claims it as 300km/162nmi. Even though they don't cite a source and could be making it up for all I know, this feels...reasonable? It's between the Irbis-E and N036, as you describe.

Since this is the only actual number I can find and it fits your broad recommendation I'm going to use 162nmi barring discovery of a different number.

Handled 508.
