### ISSUE TITLE
Moudge class metacentric height

### ISSUE THREAD

**Issue by FrangibleCover** [PygmalionOfCyprus/cmo-db-requests#4716]
### DB Selector

DB3K

### Affected DBID(s)

Ships 3754, 4408, 2090, 4127, 2550, 4128, 4359

### Summary of Changes

Given that a second Moudge has now capsized with little to no provocation, with a third lost to heavy weather in the Caspian Sea, should their Sea State ratings be lower than other frigates?

### Sources

https://www.navalnews.com/naval-news/2024/07/iranian-warship-sahand-capsizes-and-sinks/
https://warisboring.com/the-life-and-tragic-end-of-the-iranian-frigate-damavand/

**Comment by KLABDB3K** [comment]
Leaking propeller shafts apparently.
Latest is it was pulled upright then the moorings broke leading to a total capsize... Not sure CMO models lousy rope?

**Comment by PygmalionOfCyprus** [comment]
There's actually an argument to be made for reducing their sea state, but since the causes of the capsizing seems to vary and usually comes down to incompetence/failures at some level, I think this will mostly have to be like the Moskva where it's up to scenario editors to determine how incompetent they want their simulated Iranians to be.

Can be like the Polar Star in _Icebreakers_, where there's a chance for something to go wrong every hour or so. :P
