### ISSUE TITLE
China, J-20 & J-35 series, ESM device addtion

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4725]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 2463 5012 5013 5014 5454 2917 4454

### Summary of Changes

Add generic ESM [Advanced] **sensor 6096 & 6497** to all J-20 and J-35 in the database.

According to this Janes report, quotes China's state-owned media Globaltimes, we have high and full reason to believe that the PLA's fifth-generation aircrafts have some kind of ELINT system.

**If they are already done in 506, ignore this ticket**

### Sources

https://www.janes.com/osint-insights/defence-and-national-security-analysis/post/special-report-china-inducts-additional-j-20-stealth-fighters

> China's state-owned Global Times newspaper reported in February 2024 that in addition to the aircraft's stealth combat characteristics the J-20 has been equipped to execute airborne early warning and control (AEW&C) operations, supported by its “advanced sensors, computing systems, and avionics”. Such a capability suggests the J-20 is also able to integrate data from multiple other PLAAF assets.

**Comment by PygmalionOfCyprus** [comment]
So, I don't inherently disagree with this take. It makes sense that a high-end fifth-gen fighter like the J-20 would have some ESM, and that's part of why I'm so puzzled at the lack of any mention of it anywhere.

I don't know that I'm convinced by this source, though. All it says is that the J-20 has "advanced sensors, computing systems, and avionics," and hints at an integration capability. That could easily just be referring to its advanced AESA radar and an ability to network with other aircraft (prob via JSIDLS?). The fact that no one will come right out and just say it has "an advanced electronic warfare suite" or something is weird...

Compare to the F-35 (and yes I know China is far more secretive) but there's tons of sources and discussion about its onboard ESM kit. The lack of even an opaque reference to ESM for the J-20 confuses me. Is it even *possible* that China would have the J-20 flying with just a defensive ESM suite?

**Comment by LuigiP57** [comment]
I'm just an OSINT amateur, I can give reasonable information, but not enough real information that I could be a spy.

When we say that an aircraft is capable of AEW&C capabilities, the first thing we think of is what an AEW&C aircraft needs to have in order to have strong situational awareness: powerful radar, powerful ESM/SIGINT. They almost constitute the main function of the AEW&C, which distinguishes them from ordinary fighters.

So when we say that a fighter has AEW&C capability, we can basically confirm what they could have.

**Comment by PygmalionOfCyprus** [comment]
Well, yes and no. I would also argue that, especially in the context of a "quarterbacking" fighter standing in for true AEW&C, merely the presence of sensor fusion/networking and a powerful radar of its own make it viable as a stand-in AEW&C -- emphasis on the C. You have a bunch of other planes in the air, all their individual sensor info is patched in to a single J-20, that J-20 is flying in circles and ordering people around based on the combined operational picture.

China/Russia/Iran are notorious for taking a partial capacity (like this) and proudly declaring something as "capable of X". Radar detects a stealth aircraft with a non-FC quality hit at close range? "Capable of detecting stealth aircraft." UAV can drop a bomb on an enemy airfield and prevent aircraft from taking off? "Capable of seizing air superiority." J-20 can link together a bunch of sensor inputs and order other planes around based on its better COP? "Capable of AEW&C." You see the trend.

Again, I actually think adding ESM to the J-20s is a reasonable assumption because it's hard to imagine they truly don't have anything better than an RWR onboard, but it gives me pause that I can't find _any_ mention of it -- even in passing -- in a reliable source. We know the name of the radar. We know the name of the EOTS and the IRST. But we haven't even heard _mention_ of the ESM system _existing_? There's secrecy and then there's a suspicious lack of any mention whatsoever...

All I need is the slightest positive confirmation from a reputable source and I'll jump on it, but I can't even find that. This is less me disagreeing with you and moreso me saying "Let's look harder for a reliable source to confirm our suspicions."

**Comment by LuigiP57** [comment]
@PygmalionOfCyprus Then the simplest approach to uncertain but likely situation: **Hypothetical entries.** Create one for the J-20B and J-35(carrier capable version would be better), both with ELINT and OECM capabilities. In this way, we provide more choices for people with different views and needs.

**Comment by PygmalionOfCyprus** [comment]
I've added 2020 TDOA ESM to all the J-20s and J-35s. I still wish we had more proof but I just can't imagine them not having any.
