### ISSUE TITLE
China, SC-19 & DN-2, modification in some aspects

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4751]
### DB Selector

DB3K

### Affected DBID(s)

weapon 3447 4355

### Summary of Changes

- [x] Change their first 3 speed bands to **100kt-1600kt-3000kt**, same as SM-3/THAAD. The current 10kt-10kt-10kt just make its performance really strange in game

- [x] Consider modifying their PoH to **85%**. Since China has been developing ABM system for a really long time, achieving a considerable number of successful ABM test, while possesing rich and varied BMs & HGVs for testing.

- [ ] Consider **adding more TELs** to the SC-19 & DN-2 facility. 8 TELs, for example.

- [x] Increase command link channel from current 1 to 16 (take hq-9b as an example)

### Sources

https://zh.wikipedia.org/wiki/%E5%8F%8D%E5%BC%B9%E9%81%93%E5%AF%BC%E5%BC%B9#_%E4%B8%AD%E5%8D%8E%E4%BA%BA%E6%B0%91%E5%85%B1%E5%92%8C%E5%9B%BD
https://armyrecognition.com/news/army-news/2021/chinese-hq-19-anti-ballistic-missile-interceptor-presumably-operational
https://www.globalsecurity.org/space/world/china/abm.htm

**Comment by PygmalionOfCyprus** [comment]
Handled 508. Also fixed the SC/HQ-19 mounts, which were set to 1x missile per but are pretty clearly 2x in images. Increased DN-2 TEL count to 4x/Bty but kept the SC-19s the same, it looks like they're not deployed in huge batteries? Welcome a source to confirm otherwise.

![image](https://github.com/user-attachments/assets/9f380d5f-0227-4e6b-b449-2eedd03699b9)
