### ISSUE TITLE
Add Sri Lankan F-7GS Fishcan [Mig-21 Copy] 2008

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4777]
### DB Selector

DB3K

### DBID to Copy

Aircraft 1344

### Hypothetical

Yes

### Name

F-7GS Fishcan [Mig-21 Copy] 

### Country

Sri Lanka

### Service

Air Force

### In Commission

2008-present

### Number in Service

6x

### Loadout Options

Seems like AAW loadouts only!

AAW: 4 PL-5E, 1 720 Droptank
AAW: 2 PL-5e, 1 720 Droptank, 2 480 Drop Tank

### Sources

https://airfighters.com/photo/90910/M/Sri-Lanka-Air-Force/Chengdu-F-7GS/SFI-5104/
https://www.airliners.net/photo/Sri-Lanka-Air-Force/Chengdu-F-7GS/2050288
https://www.airhistory.net/photo/169205/SFI5108

Sipri 
Sri Lanka	China	2007	?	4	?	F-7MG	fighter aircraft	4	?	2008	New	Possibly aid; F-7GS version; no. may be 6
Sri Lanka	China	2007	?	25	?	PL-5E	SRAAM	25	?	2008	New	For F-7GS combat aircraft	0.11	2.75	2.75

**Comment by PygmalionOfCyprus** [comment]
Pretty sure they have A2G loadouts as well because the upgrades for the F-7GS included improved stores management, CCIP/CCRP calculation, etc. Weird that they got PL-5E instead of PL-9 when F-7GS included an HMS for the PL-9 andPL-8/9 compat was a big part of the J-7G upgrade...I almost wonder if SIPRI mis-IDed the AAMs considering they have the same bodies.

Anyway, handled 508.
