### ISSUE TITLE
China, Type 054AG FFG, extended helipad, new sensors and weapon

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4869]
### DB Selector

DB3K

### DBID to Copy

Ship 4725

### Hypothetical

No

### Name

Type 054AG Jiangkai II Mod

### Country

China

### Service

PLAN

### In Commission

2025

### Sensors

- [x] Replace the Type 364 with Type XXX X-Band radar

### Mounts

- [x] Replace the 76mm Gun with 100mm Gun on 054B

### Other Changes

- [ ] hanger and helipad replace with medium 12-18m size
- [ ] Change its length to 136m
- [ ] CS Gen 6

### Sources

https://www.sinodefenceforum.com/t/054-a-ffg-thread-ii.4149/page-578
![image](https://github.com/user-attachments/assets/9f233675-5029-45ba-a99d-95f7f80dcad0)
https://www.sinodefenceforum.com/t/054-a-ffg-thread-ii.4149/page-579
![image](https://github.com/user-attachments/assets/b29a7e29-7342-4711-820d-5a6b6f2369b2)
https://www.oni.navy.mil/Portals/12/Intel%20agencies/China_Media/2024_Recce_Poster_PLAN_Navy__U__new2.jpg?ver=gLEmUaAtttQXpV9cL9g7YA%3d%3d
![image](https://github.com/user-attachments/assets/b01725ab-de2a-4581-9e4a-640f06245a5f)

**Comment by LuigiP57** [comment]
#4858

**Comment by yU2187sie** [comment]
According to OSINT, the Type 054B will be similar to the Type 054 and the Type 054A, it will serve as a technical test ship for the newer class 054C, so the Type 054B is likely to be built in small numbers like the Type 054.

**Comment by LuigiP57** [comment]
Apparently 100mm gun rather than 76mm gun, according to its shape
https://www.sinodefenceforum.com/t/054-a-ffg-thread-ii.4149/page-580#post-1104490
![image](https://github.com/user-attachments/assets/17cfae4c-8ae4-4a4a-b28a-07253419c1d6)

**Comment by PygmalionOfCyprus** [comment]
Handled 509. I have actually reassigned ID 4725 to this unit because it looks like there was a bit of a mistake when implementing the YJ-83B variants. I had created a "new" version of the Batch 5 (Ziyang), dated 2021, to represent implementation of the YJ-83B...but in fact Ziyang was not commissioned until 2022, so this entry didn't make a lot of sense. Now Batch 5 has the YJ-83B (and HQ-16C) as standard and the errant entry now stands in for the 054AG.
