### ISSUE TITLE
China, PLAAF & PLANAF, Towed Decoy

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4875]
### DB Selector

DB3K

### DBID to Copy

weapon 3386

### Hypothetical

No

### Name

China Towed Decoy

### Country

China

### Service

PLAAF & PLANAF

### Other Changes

- [ ] May add **4x** mount (same as F/A-18E/F and F-35) on **Aircraft 2917 2463 4454 4632 4817 4926 5013 5454 6098** (newer version of J-20, J-16/D, J-15B/D and J-35)

For a long time, we have believed that the PLA is not equipped with a Towed Decoy like the AN/ALE-70 FOTD.The most conservative estimate is for the new J-20 version appear in 2020s. However, due to my casual curiosity these days, I found information about the Chinese version of FOTD on SDF.

The first is a very China-Official photo of a Department working on a FOTD Pod modification project for the J-20. At the same time, I noticed another demonstration from the China Air Show that the Flanker had a tow decoy that could be released from its tail cone. And a reliable Chinese OSINT article also hinted at the possibility of using this equipment on the J-16 and other more advanced fighters.

### Sources

https://www.sinodefenceforum.com/t/j-20-5th-generation-fighter-vii.8678/page-418#post-772854
![image](https://github.com/user-attachments/assets/e73463a1-7bfc-4a0d-ad87-2ec51155dfe0)
https://www.sinodefenceforum.com/t/j-20-5th-generation-fighter-vii.8678/page-419
![image](https://github.com/user-attachments/assets/b3deacc1-5cdb-47e3-81e0-68ca60acbf88)
https://chinese-military-aviation.blogspot.com/
![image](https://github.com/user-attachments/assets/a287d1f4-947c-4745-b8d3-4be47ddc8ef7)

**Comment by LuigiP57** [comment]
Given that the published photos show that the tail cone of the J-16 is still loaded with a retarder parachute, I remain skeptical about the use of Towed Decoy for advanced aircraft other than the J-20B/S and J-35.
![image](https://github.com/user-attachments/assets/4c07c018-7c19-4fbb-a2d3-8326b71eb834)
![image](https://github.com/user-attachments/assets/8452c4d8-1e25-49e6-8f74-6e98afb4a95e)

**Comment by PygmalionOfCyprus** [comment]
I suspect if there are towed decoys on older-gen fighters like the J-15/15 it is probably more like the AN/ALE-50, e.g. an under-pylon mount. But I agree I don't think we have seen any evidence of this yet.

One thing I'm unsure of is where this would be located on a J-20. There's no tailcone and I can't see a port that might contain it on the underside like there is on the F-35.

![image](https://github.com/user-attachments/assets/7c2ac906-c872-4b74-be68-24082ca44169)

I suppose it could be contained in the weapons bay? But that seems silly, because by opening the weapons bay you create a much larger target out of yourself...I wonder if this is technology they are developing but have not yet integrated into the J-20. I'd bet it's probably just a pylon-based solution like the ALE-50 right now.

I have added it to the DB and created a mount but am not adding it to any aircraft yet.
