### ISSUE TITLE
China, GJ-11 aircraft FT-7 Loadout

### ISSUE THREAD

**Issue by yUsie108** [PygmalionOfCyprus/cmo-db-requests#4914]
### DB Selector

DB3K

### User(s)

PLAAF GJ-11

### Weapons Carried

-8x FT-7 Flying Strides SDB [GPS,135kg HE Penetrator]

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

In the new version, the Loadout of the GJ-11 is adjusted to only mount the LT-2, while the actual case of the GJ-11 mounting the FT-7 has been shown.

### Sources

![image](https://github.com/user-attachments/assets/1bcea28e-d72d-4beb-b964-51a5f04cda57)

**Comment by PygmalionOfCyprus** [comment]
We removed the FT-7 loadouts because we cannot find any indication that the FT-7 has actually been acquired by the PLA. Of course it is technically possible, as shown in the image; we were aware of these mockup presentations, but many weapons have been shown at airshows without actually entering service. In general the PLA still has a real dearth of fielded PGMs, despite all the options offered by industry.

The loadout is still in the DB (Loadout 27826), so you can add with Lua if you really need it.
