### ISSUE TITLE
RIM-174A SM-6 Blk IB Correction

### ISSUE THREAD

**Issue by FRF312** [PygmalionOfCyprus/cmo-db-requests#4942]
### DB Selector

DB3K

### Affected DBID(s)

weapon 3772,3714

### Summary of Changes

change its warhead from SM-3 Kinetic into RIM-156B 62kg ABM-Optimized Frag

### Sources

Maybe it's a copy entry error from SM-3,like the 1325nm range bug found before?Frag is actually more effective against land and sea targets.

**Comment by HunterDNiu** [comment]
Dup #4898 
I think the search function is also down? @PygmalionOfCyprus

**Comment by PygmalionOfCyprus** [comment]
We were sort of guessing at the warhead based on rumbles that the SM-6 Blk IB is getting "a new 'warhead design'" ([as per AviationWeek](https://aviationweek.com/defense/missile-defense-weapons/document-likely-shows-sm-6-hypersonic-speed-anti-surface-role)). The baseline SM-6 frag is not considered appropriate for ASuW.

Since the main effector of a hypersonic weapon is going to be its velocity and not its explosive warhead we went with the kinetic warhead, figuring they might just yoink it from the SM-3 like so many other components. But if we get more indication of what that warhead might actually be ofc we'll modify it.
