### ISSUE TITLE
HIPRI PLAGF ZBD-08 HJ-10 Carrier

### ISSUE THREAD

**Issue by FRF312** [PygmalionOfCyprus/cmo-db-requests#4944]
### DB Selector

DB3K

### Affected DBID(s)

facitily 3195

### Summary of Changes

What's this?It makes me very confused.And it can't be add into the scenarios.
ZBD-08 HJ-10 Carrier has been in PLAGF service for several years. And weapon it used should be changed into AFT-10 from AKD-10 while AFT-10 doesn't have carrier platfroms now.
### Sources

![image](https://github.com/user-attachments/assets/1d6c19e0-02ab-4a7c-b068-a67abce85c81)

**Comment by PygmalionOfCyprus** [comment]
The "1x Vehicle" facility entry for the ZBD-04/08 was moved to the Junkyard because such entries are deprecated and unnecessary with the new Ground Units annex. (If you're trying to place down a single vehicle you should be using GUs.)

There is a Mech Inf Plt for the ZBD-04A/ZBD-08, but I see I neglected to add one for the ZBD-04A AT variant. I've added a Plt for this variant as well in 509.
