### ISSUE TITLE
China, KF-21 ALBM & HGV update

### ISSUE THREAD

**Issue by Luigi-II** [PygmalionOfCyprus/cmo-db-requests#5104]
### DB Selector

DB3K

### Affected DBID(s)

weapon 3564 3565 4481 4482

### Summary of Changes

- [ ] Add **sensor 4370 4371 (KF-21 RV, DF-21D RV sensor group)** to KF-21 HGV (weapon 4482). This should be some kind of copy entry error.
- [ ] Increse its range to **4320nm (same as DF-27)**. You know, its a DF-26/27 size ALBM with HGV. Admittedly, some weight compromise (smaller diameter, smaller warhead) is required to mount this thing on the H-6N. Air-Launched version, without (almost) no cut in booster length or segments, should be at least assumed the same range as land-based version.
- [ ] Use same **speed pattern** as **DF-27** for **KF-21 HGV (weapon 4481 4482**). Definately not DF-21D variant but DF-27 variant.
- [ ] Use same speed pattern as **DF-26** for **KF-21 RV (weapon 3564 3565)**.
- [ ] Change **the booster (weapon 3564 4481)** **length to 13.09m, diameter to 1m**. Definately not DF-21D variant but DF-26 variant.

### Sources

DB itself
![image](https://github.com/user-attachments/assets/16fdbd30-e3b9-44fe-b3da-1e56ae409ad5)
https://www.iiss.org/online-analysis/online-analysis/2020/10/mdi-chinese-plaaf-h-6n-missile/
![image](https://github.com/user-attachments/assets/c1668c46-4fe9-4674-8f2d-c693392a29e2)

**Comment by PygmalionOfCyprus** [comment]
Not sure of your sources that this is "Definately not DF-21D variant but DF-26/27 variant"...pretty much every source seems to agree that the CH-AS-X-13 is based on the DF-21D. Also, the HGV does not have terminal guidance because we have no indication that the DF-ZF actually does have terminal guidance -- especially since radar guidance on HGVs is known to be extremely difficult due to plasma, etc.

https://www.twz.com/this-is-our-best-look-yet-at-chinas-air-launched-carrier-killer-missile
