### ISSUE TITLE
China CJ-100 missing terminal seeker

### ISSUE THREAD

**Issue by caelunshun** [PygmalionOfCyprus/cmo-db-requests#5115]
### DB Selector

DB3K

### Affected DBID(s)

Weapon 3668, 3669

### Summary of Changes

CJ-100 is listed as capable against surface targets but lacks a terminal seeker. This means it can never hit a ship target, at least in my testing. Suggested fix: either  (a) remove the surface attack capability or (b) add a seeker (active radar or IR?)

### Sources

DB, no extra source needed

**Comment by PygmalionOfCyprus** [comment]
This is technically correct but probably a result of Command not handling GNSS guidance against large warships perfectly.

AFAIK the CJ-100 does not have a terminal seeker IRL and is primarily a land-attack missile, but because of it's GNSS guidance it is advertised as capable against "large surface warships". I mean, yeah, if you had a consistent track you could probably pass updated coordinates as it moves and get close enough to score a hit. But I think Command doesn't consider that as possible.

I'll remove the surface capable flag b/c when we implement that as a possibility I think we'll just have it be automatically applied to all weapons with GNSS guidance and a suitable small CEP, or something.

Handled 509.
