### ISSUE TITLE
[HIPRI] China, problems with HHQ-9B and HQ-9B

### ISSUE THREAD

**Issue by yU2187sie** [PygmalionOfCyprus/cmo-db-requests#5339]
### DB Selector

DB3K

### Affected DBID(s)

weapon 4090 3763

### Summary of Changes

In the latest 509 DB release, I found a change to the HHQ-9B that adjusted its minimum target altitude to 10m, which made it impossible to fire against a significant number of sea-sweeping anti-ship missiles.
Take the YJ-18 missile, which the PLAN has made public for some time, an anti-ship missile that uses subsonic sea skimmings in the first half of its flight, separating out the rocket-powered warhead design during penetration. It is impossible that the HHQ-9B system on the PLAN ship has not been tested against it. The current situation is facing sea-skimming YJ-18, which should normally be discovered and quickly destroyed to prevent its rocket-powered warhead from being released. However, due to the modification of the minimum target altitude, the YJ-18 **flying at 9.1m** in the state of sea skimming flight, the HHQ-9B with **the lowest target altitude of 10m** **cannot be launched at all**, which is obviously not in line with reality.
Even in the face of the world famous sea sweeping anti-ship missiles such as the French Exocet missile and the United States AGM-84 missile series, because the current **lowest Target Altitude** of HQ-9B is only **10m**, in the face of these sea sweeping targets **flying at a height of** **9.1m**, HHQ-9B is **completely unable to launch**.
Similarly, the land-based HQ-9B system also has the same problem. And HQ-9B & HHQ-9B both possess upgraded ARH from HQ-9A，so better change both of them.
Modifications are proposed here.

- [ ] Reset the minimum target altitude of HQ-9B and HHQ-9B back to 9.1m.

### Sources

DB itself.

**Comment by Luigi-II** [comment]
Ah... That's the problem again, just like I complained about the anti-ship missile's altitude. Most of the typical sea-skimming missiles in the game use a cruise altitude of 30ft/9.1m, which is a fixed value. In reality, the altitude of these missiles can change from time to time (based on range, aerodynamic performance, and seeker search requirements). eg. "cruise at 5-10m or more."

The ship-based SAMs, which different from some land-based SAMs, specialize against sea-skimmer, meaning they have a lower interception altitude. For example, the seeker is better at filtering out sea clutter to help locking on targets. But that's not the problem here! The minimum height of SAM is only a "reference value" rather than a "fixed value", and it does not mean that the "minimum interception height is 10m" thus it can not intercept the "9.1m cruising" target, even the HE frag can cover a range of several meters.

HHQ-9 intercepting sea-skimming targets:
https://www.youtube.com/watch?v=_pezJKg4M98

**Comment by Luigi-II** [comment]
I even got some evidence shows that HHQ-9A could do that too. HHQ-9A fired from a Type 052C (see the CIWS on hangar, it only could be a 052C)
![image](https://github.com/user-attachments/assets/637815ac-5c36-4d76-85ee-8e6d3c0a93b0)
![image](https://github.com/user-attachments/assets/db6b11f7-30d9-433d-b16a-e215d46e1ff8)
![image](https://github.com/user-attachments/assets/50d3de7d-f621-473b-99f4-bc50bea2171a)
![image](https://github.com/user-attachments/assets/c02d1d02-c58c-4a7b-8a0d-4fc173222832)
![image](https://github.com/user-attachments/assets/3d7c9761-b8a2-441a-902e-7dac78591ff8)
![image](https://github.com/user-attachments/assets/f26321bb-346b-441a-920f-0c720529a348)

**Comment by Luigi-II** [comment]
I think the source of this problem has something to do with this.
![image](https://github.com/user-attachments/assets/54fbd45e-4034-4cba-8252-e2633b37afe9)
Well, here's my own take: When it comes to different units of length, there can be two ways to say same thing. When we say, "A SAM can intercept sea-skimming targets," we pick a unit as a "minimum" reference. For countries where imperial units are used, they may say 30ft/9.1m instead of 33ft/10m. For countries that use metric units, they might say 10m instead of 9.1m. If we don't realize that there are two systems of measurement in this game, and how they relate to reality, then we will make a big mistake!

**Comment by Jkryos** [comment]
Fixed DB3K 510.
