### ISSUE TITLE
Mixed Sparrow and Amraam Escort Loadout on Israeli F-15C

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#715]
### DB Selector

DB3K

### User(s)

3207, 3657,4819, 3208, 3656

### Weapons Carried

2 Sparrow
2 Amraam
2 Python 5
ELL-8222 ECM jammer pod
Can add typical 2 drop tanks for longer range.

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Sources

https://twitter.com/GuyPlopsky/status/1454480257591828484/photo/2
https://www.youtube.com/watch?v=E_UNEHbtGHc

**Comment by Huib18** [comment]
Extra source:
https://www.thedrive.com/the-war-zone/39648/israeli-f-15s-were-armed-with-old-missiles-during-b-52-escort

**Comment by bostonmyk** [comment]
Amraam
https://twitter.com/sariel_stiller/status/1461996568433897475/photo/1

**Comment by Huib18** [comment]
The purpose of these messages is, that the IAF sometimes still flies with older missiles and that this option is available in the loadouts of CMO. Maybe it is because a MiG-21 or MiG-23 or UAV of Syria is not worth an expensive AIM-120 and a AIM-7 Sparrow will do.
For Egypt the situation can be different. The IAF does fly with AMRAAMS that's for sure.

**Comment by PygmalionOfCyprus** [comment]
Added 495.
