### ISSUE TITLE
Add KJ-1 AEW (Tu-4 Mod)

### ISSUE THREAD

**Issue by Coiler12** [PygmalionOfCyprus/cmo-db-requests#76]
### DB Selector

Both

### Hypothetical

Yes

### Name

KJ-1 AEWC (Tu-4 Mod)

### Country

China

### Service

Air Force

### In Commission

1974

### Length (m)

30.18

### Wingspan (m)

41

### Height (m)

12.5

### Empty Weight (kg)

34600

### Maximum Takeoff Weight (MTOW) (kg)

69700

### Payload Weight (kg)

0

### Crew

12

### Propulsion

4x AI-20M Turboprop

### Rate of Climb (ft/min)

890

### Service Ceiling (ft)

36000

### Military/Afterburner Speed (kt)

301

### Cruise Speed (kt)

222

### Supercruise

No

### Ferry Range (nm)

4800

### Endurance (min)

2160

### Takeoff / Landing Distance (m)

901/1400

### Fuel Capacity (kg)

65710

### Sensors

1x KJ-1 Radar
1x Generic ESM (Simple)
1x Mk 1 Eyeball 

### Mounts

None

### Loadout Options

Airborne Early Warning

### Comms/Datalinks

UHF Radio (Secure)
VHF Radio (Secure)
HF Radio (Secure)

### Aircraft Codes

Night Navigation (Ferry, Air-to-Air, Air-to-Surface Missiles)

### Comments

Will include the KJ-1 Radar as a separate sensor issue. Endurance may be too high-I used a normal Tu-4 with a ferry loadout and used the time till bingo fuel for that. 

### Sources

http://www.airwar.ru/enc/spy/hh2.html (in Russian)
https://www.globalsecurity.org/military/world/china/kj-1.htm
https://en.wikipedia.org/wiki/KJ-1_AEWC

**Comment by PygmalionOfCyprus** [comment]
Linked to #77

**Comment by PygmalionOfCyprus** [comment]
Added to CWDB 509. Not adding to DB3K because the project was cancelled before 1980, and yes in a hypothetical world where it entered service it would have been in the DB3K timeframe, but you could say that about a lot of things and I don't think people are clamoring for the KJ-1 in 3K the way they might for, say, an updated Tomcat. Frankly the pain of doing a cross-DB transfer has kept me from tackling this ticket for years, and it's spiritually a CWDB ticket, so I think this is better than letting it continue to languish.
