### ISSUE TITLE
Sukhoi Checkmate changes

### ISSUE THREAD

**Issue by Coiler12** [PygmalionOfCyprus/cmo-db-requests#780]
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 5327

### Summary of Changes

Some Su-75 Checkmate changes.

1: Should be flagged as hypothetical. Even before the Ukraine war, it arguably deserved this flag due to the lack of info and no firm orders. After the war/sanctions/economic difficulties, it deserves much more so. 
2: Supposedly benchmarked against the F-117 in terms of stealth (see patent source). While it's already in the same ballpark in terms of its existing signature, especially when its physically smaller size is taken into account, it might be worth taking a look at. 
3: Should have the ability to carry and drop KAB-250S (Weapon 3579) and KAB-500S (Weapon 3340) satellite "JDAMskis". It's advanced and the weapons are smaller than those it currently carries. 

### Sources

https://new.fips.ru/registers-doc-view/fips_servlet?DB=RUPAT&rn=2005&DocNumber=2768101&QID=0259937B-597E-4B5C-AA56-FCE718499776&TypeFile=html

**Comment by KLABDB3K** [comment]
Definitely in the Hypothetical section. 
If even countries with "issues" about their human rights are reconsidering Russian purchases and are worried about the risk of collateral sanctions I do not see a future for this.

**Comment by PygmalionOfCyprus** [comment]
Yeah, this is 100% vaporware.

Dare I say it's checkmate for the Checkmate?

**Comment by tbrandon517** [comment]
Real as a ![qaher-313-640_49444](https://user-images.githubusercontent.com/99599482/160149345-1d375c7f-83d6-4bcf-8a7e-de5aadccce20.jpg)

**Comment by bostonmyk** [comment]
Saw this on Twitter the other day.  https://twitter.com/TheDEWLine/status/1507120268870832135

**Comment by TempestII** [comment]
I don't think there's anything wrong with having the Checkmate in as hypothetical, but giving it a low RCS has to be unrealistic. It might now even be as LO as the FELON, which is probably the least VLO 5th Gen flying at the moment. 

https://www.19fortyfive.com/2021/11/su-75-is-russias-new-stealth-fighter-actually-stealth/

**Comment by Coiler12** [comment]
> I don't think there's anything wrong with having the Checkmate in as hypothetical, but giving it a low RCS has to be unrealistic. It might not even be as LO as the FELON, which is probably the least VLO 5th Gen flying at the moment.
> 
> https://www.19fortyfive.com/2021/11/su-75-is-russias-new-stealth-fighter-actually-stealth/

Then again, the whole aircraft was "unrealistic" even before the war (just look at its supposed cheap price tag!) and the primary source patent (as opposed to that speculative article) clearly called for it to be like the F-117.

**Comment by PygmalionOfCyprus** [comment]
On hold pending completion of PygmalionOfCyprus/cmo-db-dev#178

**Comment by PygmalionOfCyprus** [comment]
Fixed 494: hypotheticalized (hypothesized?); and KAB-250S, KAB-500S loadouts added.

I will come right out of the gate and admit I don't speak Russian well enough to decipher technical writing (much to the chagrin of my grandmother, no doubt), so I'm relying on machine translation for this. But are we _sure_ the patent is specifically saying they want to achieve F-117-equivalent stealth performance?

It seems like the patent is primarily concerned with creating a stealthy aircraft that preserves fighter-grade maneuverability (the F-117 is mentioned as an example of a stealthy aircraft that had to sacrifice maneuverability for its stealth). It says

> However, the disadvantage of [the F-117] is poor takeoff and landing characteristics, as well as insufficient stability and controllability of the aircraft.

> The task of the [Checkmate] is to eliminate the shortcomings of aircraft known from the level of technology.

> Thus, the technical result of which the declared invention is aimed at is an increase in the stability and handling of the aircraft without degrading the characteristics of radar visibility.

It doesn't specifically say "we want to achieve the same stealth as the F-117." 

It sounds more like they're basically patenting an aircraft with stealthy control surfaces, rather than specifically an aircraft matching F-117 stealth levels. This is supported by the fact that the patent goes into great detail on control surfaces but not at all about stealth features -- even basic shaping stuff, which could be safely discussed in a patent filing.

Hypothetical or not, I share @TempestII's serious, serious doubts about the Checkmate achieving an ultra-low RCS. The Su-57, Russia's "crown jewel" stealth fighter up to now, is nowhere _near_ that stealthy -- and while the Checkmate does incorporate new institutional knowledge and a few features that didn't make it into the Su-57, I just don't think an aircraft intended as a cheap export fighter is going to magically overcome the serious challenges that have plagued the Russian stealth program until now. Nor, frankly, do I think it was even supposed to.

At best I'd say the Su-75 is a fighter with low-observable characteristics, not a low-observable fighter. I've given it the modifiers to match.

With the new modifier overhaul, this will put the Su-75 at slightly less stealthy than the Su-57 (remember the Su-57 is almost a third bigger), which is much less stealthy than a J-20, which is itself MUCH less stealthy than an F-22 and the even-stealthier F-35. I think that's fair.

If the Russians want to prove it's as stealthy as they'd like us to believe they can start by building the thing. Then we'll see. (Or, perhaps they'd rather we didn't. Since that's sort of the whole point. 😏)

**Comment by bostonmyk** [comment]
Sounds good! Willing to bet this program is stalled, if not killed, given what they'll have to replace after Ukraine.
