### ISSUE TITLE
weapon #718 (AIM 120C-7) has the description of the MIM-23 Hawk

### ISSUE THREAD

**Issue by FDA81** [PygmalionOfCyprus/cmo-db-requests#835]
Hello
I have command 1.04 build 1147.42

**Comment by claudejdev** [comment]
> Hello I have command 1.04 build 1147.42

Hey FDA81,

The description pack isn't managed by the same person as the Database.
You can reach out to CV60, the description team head, on the forum : [Review and Editing of Unit Descriptions](https://www.matrixgames.com/forums/viewtopic.php?p=4895117#p4895117)

I've reported the issue you mentioned. It might be fixed in the next update (you might have to delete the file manually though) : [RE: IDEA/PROPOSAL: Community creation/review of unit description](https://www.matrixgames.com/forums/viewtopic.php?p=4956392#p4956392)

Kudos for the effort of posting a report, by the way 👍🏻

**Comment by FDA81** [comment]
Thank you! I already posted another request, sorry!
