### ISSUE TITLE
weapon #718 (AIM 120C-7) and #817 (500 USG conformal tank) have the description of the MIM-23 Hawk

### ISSUE THREAD

**Issue by FDA81** [PygmalionOfCyprus/cmo-db-requests#836]
### DB Selector

CWDB

### Affected DBID(s)

718, 817

### Summary of Changes

Remove or change "GENERAL DESCRIPTION"

### Sources

in game database

**Comment by claudejdev** [comment]
> ### DB Selector
> CWDB
> 
> ### Affected DBID(s)
> 718, 817
> 
> ### Summary of Changes
> Remove or change "GENERAL DESCRIPTION"
> 
> ### Sources
> in game database

> Hello I have command 1.04 build 1147.42

Hey FDA81,

The description pack isn't managed by the same person as the Database.
You can reach out to CV60, the description team head, on the forum : [Review and Editing of Unit Descriptions](https://www.matrixgames.com/forums/viewtopic.php?p=4895117#p4895117)

I've reported the issue you mentioned. It might be fixed in the next update (you might have to delete the file manually though) : [RE: IDEA/PROPOSAL: Community creation/review of unit description](https://www.matrixgames.com/forums/viewtopic.php?p=4956392#p4956392)

Kudos for the effort of posting a report, by the way 👍🏻
