### ISSUE TITLE
5416 - Quadcopter UAV - fuel consumption too high, RTB immediately after launch

### ISSUE THREAD

**Issue by AndrewJ12** [PygmalionOfCyprus/cmo-db-requests#915]
### DB Selector

DB3K

### Affected DBID(s)

5416

### Summary of Changes

"Quadcopter UAV -- Generic"  fuel quantities and fuel consumption are such that the Quadcopter has a "0 nm Area Surveillance Radius".

Quadcopters instantly RTB (Bingo) after they are launched.

Please adjust fuel consumption downwards to give them a reasonable range/duration. (Unfortunately, I have no idea what that would be. An hour or so? Definitely more than zero!)

Thanks very much.

### Sources

I'm not sure what the flight time for a generic quadcopter would be, but it has to be more than zero.

**Comment by claudejdev** [comment]
The endurance for that kind of UAV seems to be 30 minutes.
Cf. Gettinger, D., & Bard College. (2019). [The Drone Databook](https://dronecenter.bard.edu/projects/drone-proliferation/databook/).

**Comment by claudejdev** [comment]
Another open source for such a generic drone:
https://odin.tradoc.army.mil/WEG/Asset/Evo_II_American_Remote_Controlled_Quadcopter

- Maximum Horizontal Speed :  20 m/s
- Flight Ceiling : 7000 m
- Maximum Flight Time : 40 Minutes
- Maximum Hover Time : 35 Minutes

An interesting parameter, since it's remotely controlled : Maximum Operating Distance : 9 km at 2.4 G
