### ISSUE TITLE
Brazil - KC390 Refueling Capability

### ISSUE THREAD

**Issue by LucasSFCMANO** [PygmalionOfCyprus/cmo-db-requests#942]
### DB Selector

DB3K

### User(s)

#4013 EMBRAER KC390 

### Weapons Carried

2X WING DROGUE REFUELING

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

Add DROGUE Refueling Capability to the KC-390

Certified for Aircraft and Helicopters

By 2017, the KC-390 had conducted the first FAB fighter “dry contact” tests. In this type of operation the aircraft connect, but there is no fuel transfer.

Embraer’s multi-mission freighter, recently named C-390 Millennium, can refuel other aircraft in flight through two wing-mounted probes, delivering up to 1,500 liters of fuel per minute. At this rate you can replenish the F-5 and A-1M internal tanks in less than two minutes.

Using three extra tanks, the KC-390 can carry a total of 35 tons of fuel – the aircraft’s standard capacity is 23 tons. According to Embraer data, the aircraft is capable of performing aerial refueling operations at speeds between 220 km/h and 560 km/h at altitudes ranging from 610 meters to 9,750 m

### Sources

https://forcaaerea.com.br/kc-390-e-certificado-pelo-dcta-para-missoes-de-revo/

https://forcaaerea.com.br/dois-kc-390-da-embraer-realizam-missao-revo-noturna/

https://www.fab.mil.br/noticias/mostra/29267/KC-390%20-%20Futuro%20cargueiro%20da%20FAB%20realiza%20primeiro%20procedimento%20de%20REVO%20em%20ca%C3%A7as

https://aeroin.net/veja-como-funciona-o-reabastecimento-em-alta-velocidade-do-kc-390-da-embraer/kc-390-fab-revo-reabastecimento-amx/

**Comment by claudejdev** [comment]
Piggybacking on that one, if you don't mind, to add : 

ID | Name
--- | ---
4013 | C-390 Millennium (Brazil - 2018)
5341 | C-390 Millennium (Hungary - 2023)
5342 | C-390 Millennium (Portugal - 2023)

for all ID
`4013, 5341, 5342`

- > Update its agility in par with similar platform [^1]. _The cockpit and windows are protected against up to .50-caliber rounds._ [^2]

Update DataAircraft.Agility = 1, DataAircraft.AircraftCockpitArmor = 1015

- > The C-390 avionics suite also includes a terrain-avoidance and warning system (TAWS) [^2] 

New DataAircraftCodes.CodeID = 6001

- > Replace #970 - Generic Doppler Navigation/Weather by #6469 - Selex T-20 radar [^3]

Update DataAircraftSensors.ComponentID = 6469 WHERE ComponentNumber = 1

[^1]: DB3K_493 similar platforms 
[^2]: Aviation Week Network, Profile 1182 (Open source behind a paywall. Could provide a pdf by PM)
[^3]: > For situational awareness, the C-390 carries the Selex Galileo Gabbiano T20 air-cooled, mechanically scanned, low-power X-band radar. The T20 covers a 180-degree arc cone in front of the aircraft. It features electronic counter-countermeasures, a track-while-scan capability and synthetic aperture radar (SAR) and ground moving target indicator (GMTI) modes. It is ideal for search-and-rescue operations at sea because of its ability to track search-and-rescue transponder (SART) beacons, and can also be used to support tactical navigation in its ground mapping, weather and terrain avoidance modes.  Aviation Week Network, Profile 1182

**Comment by PygmalionOfCyprus** [comment]
Implemented Claude's changes. The refueling capability is already covered by loadout 29629.
